const toastEl = document.querySelector('#toast');
const modalEl = document.querySelector('#modal');
const notifyPopupEl = document.querySelector('#notifyPopup');
const navLinks = document.querySelector('#navLinks');
const languageSelect = document.querySelector('#languageSelect');
let toastTimer;

const translations = {
  en: {
    pageTitle: 'BloodNet - Smart Blood Donor Network',
    brandTag: 'Smart Blood Donor Network',
    langLabel: 'Language',
    headerExplore: 'Explore roles',
    headerRequest: 'Raise request',
    heroPill: 'AI-powered · Real-time',
    heroTitle: 'Every second counts. Every donor matters.',
    heroDesc: 'An AI-powered network connecting donors, hospitals, and blood banks so the right donor is found in seconds, not hours.',
    ctaPrimary: 'Become a donor',
    ctaSecondary: 'See how it works',
    statDonors: 'Active donors',
    statHospitals: 'Partner hospitals',
    statLives: 'Lives impacted',
    statResponse: 'Avg. response',
    criticalTag: 'CRITICAL REQUEST · 2 MIN AGO',
    liveTag: 'Live',
    liveTitle: "St. Martha's Hospital · O+ blood",
    liveDesc: '2 units · 3.2 km away',
    notifyTop: 'Notify top donors',
    featuresEyebrow: 'Built for life-or-death moments',
    featuresTitle: 'Ten capabilities that turn a manual scramble into a coordinated response.',
    feature1Title: 'Emergency Alerts',
    feature1Desc: 'Push notifications reach top-ranked donors the instant a request is raised.',
    feature2Title: 'AI Availability Prediction',
    feature2Desc: 'XGBoost-style scoring helps estimate who is most likely to respond now.',
    feature3Title: 'Priority Ranking',
    feature3Desc: 'Weighted by distance, recency, response history, and the AI signal.',
    feature4Title: 'History & Badges',
    feature4Desc: 'Donation milestones, certificates, and recognition for consistent donors.',
    feature5Title: 'Map Search',
    feature5Desc: 'Find compatible donors within a radius, ranked by relevance instead of random order.',
    feature6Title: 'Admin Analytics',
    feature6Desc: 'Monitor demand, fulfilment speed, and donor retention from one dashboard.',
    rolesEyebrow: 'One platform · Four roles',
    rolesTitle: 'Each user gets a focused experience for their part in the response chain.',
    role1Mark: 'Donor',
    role1Title: 'Receive alerts and track impact',
    role1Desc: 'See matched requests, respond quickly, and keep your donation history visible.',
    role2Mark: 'Hospital',
    role2Title: 'Raise emergencies instantly',
    role2Desc: 'Trigger a request, match eligible donors, and follow the response in real time.',
    role3Mark: 'Blood Bank',
    role3Title: 'Manage live inventory',
    role3Desc: 'Track blood units, monitor supply pressure, and coordinate fulfilment across hospitals.',
    role4Mark: 'Admin',
    role4Title: 'See the whole network',
    role4Desc: 'Use live metrics, retention insights, and regional activity to keep the system responsive.',
    impactEyebrow: 'Why it works',
    impactTitle: 'Designed to reduce delay at every step.',
    impactDesc: 'BloodNet combines compatibility rules, ranked recommendations, and a clear response workflow so teams spend less time searching and more time acting.',
    faqEyebrow: 'Frequently Asked Questions',
    faqTitle: 'What it is, why it helps, and why it stands out.',
    faq1Question: 'What is it?',
    faq1Answer: 'BloodNet is a donor network that connects hospitals, donors, and blood banks in one place.',
    faq2Question: 'Why is it useful?',
    faq2Answer: 'It saves time, finds the right donor faster, and speeds up the response during emergencies.',
    faq3Question: 'Why is it better than others?',
    faq3Answer: 'It matches by priority, distance, and availability, so the search is not random.',
    faq4Question: 'Is it easy for hospitals?',
    faq4Answer: 'Yes, hospitals can raise a request in a few clicks and notify matched donors immediately.',
    faq5Question: 'Does it really help?',
    faq5Answer: 'Yes, faster matching, a clear process, and live notifications improve the chance of help arriving on time.',
    footerBrandDesc: 'Smart Blood Donor Network',
    footerTeam: 'Project Team',
    team1: 'Angel Blessy (2547213)',
    team2: 'Enrita Fernandes (2547223)',
    footerLinks: 'Quick Links',
    footerLink1: 'Features',
    footerLink2: 'Roles',
    footerLink3: 'Impact',
    legal1: 'MCA 2025–27 · CHRIST (Deemed to be University), Bangalore Central Campus',
    legal2: '© 2026 BloodNet',
    modalTitle: 'Raise emergency request',
    modalDesc: 'This demo simulates the hospital-to-donor workflow.',
    fieldTitle: 'Patient / request title',
    fieldTitlePlaceholder: 'e.g. Trauma patient',
    fieldBloodGroup: 'Blood group',
    fieldUnits: 'Units needed',
    modalSubmit: 'Notify matched donors',
    toastLanguage: 'Language changed to English.',
    toastNotify: 'Top three matched donors notified successfully.',
    toastRequest: 'Emergency request created. Matching donors are being notified.',
    ariaClose: 'Close request form',
    notifyPopupKicker: 'Notification',
    notifyPopupTitle: 'Donors notified',
    notifyPopupDesc: 'The top matched donors have been notified for the current request.'
  },
  hi: {
    pageTitle: 'BloodNet - स्मार्ट रक्तदाता नेटवर्क',
    brandTag: 'स्मार्ट रक्तदाता नेटवर्क',
    langLabel: 'भाषा',
    headerExplore: 'भूमिकाएँ देखें',
    headerRequest: 'अनुरोध भेजें',
    heroPill: 'एआई-संचालित · तुरंत',
    heroTitle: 'हर सेकंड महत्वपूर्ण है। हर रक्तदाता महत्वपूर्ण है।',
    heroDesc: 'यह एक ऐसा नेटवर्क है जो रक्तदाताओं, अस्पतालों और ब्लड बैंकों को जोड़ता है ताकि सही रक्तदाता जल्दी मिल सके।',
    ctaPrimary: 'रक्तदाता बनें',
    ctaSecondary: 'यह कैसे काम करता है',
    statDonors: 'सक्रिय रक्तदाता',
    statHospitals: 'सहयोगी अस्पताल',
    statLives: 'प्रभावित जीवन',
    statResponse: 'औसत प्रतिक्रिया',
    criticalTag: 'अत्यावश्यक अनुरोध · 2 मिनट पहले',
    liveTag: 'ताज़ा',
    liveTitle: 'सेंट मार्था अस्पताल · O+ रक्त',
    liveDesc: '2 यूनिट · 3.2 किमी दूर',
    notifyTop: 'शीर्ष रक्तदाताओं को सूचित करें',
    featuresEyebrow: 'महत्वपूर्ण क्षणों के लिए बनाया गया',
    featuresTitle: 'ऐसी क्षमताएँ जो हाथ की भागदौड़ को एक स्पष्ट प्रतिक्रिया में बदल देती हैं।',
    feature1Title: 'आपातकालीन अलर्ट',
    feature1Desc: 'अनुरोध बनते ही शीर्ष रैंक वाले रक्तदाताओं को पुश सूचना मिलती है।',
    feature2Title: 'उपलब्धता अनुमान',
    feature2Desc: 'मॉडल यह समझने में मदद करता है कि अभी कौन प्रतिक्रिया दे सकता है।',
    feature3Title: 'प्राथमिकता रैंकिंग',
    feature3Desc: 'दूरी, हाल की गतिविधि, प्रतिक्रिया इतिहास और एआई संकेत पर आधारित।',
    feature4Title: 'इतिहास और बैज',
    feature4Desc: 'दान के माइलस्टोन, प्रमाणपत्र और नियमित रक्तदाताओं के लिए पहचान।',
    feature5Title: 'मैप खोज',
    feature5Desc: 'उपयुक्त रक्तदाताओं को दायरे में खोजें और प्रासंगिकता के अनुसार क्रमबद्ध करें।',
    feature6Title: 'प्रशासनिक विश्लेषण',
    feature6Desc: 'एक ही डैशबोर्ड से मांग, पूर्ति गति और दाता प्रतिधारण देखें।',
    rolesEyebrow: 'एक प्लेटफ़ॉर्म · चार भूमिकाएँ',
    rolesTitle: 'हर उपयोगकर्ता को उसकी भूमिका के अनुसार केंद्रित अनुभव मिलता है।',
    role1Mark: 'रक्तदाता',
    role1Title: 'अलर्ट प्राप्त करें और प्रभाव देखें',
    role1Desc: 'मिले हुए अनुरोध देखें, जल्दी प्रतिक्रिया दें, और अपना इतिहास देखें।',
    role2Mark: 'अस्पताल',
    role2Title: 'तुरंत आपात अनुरोध भेजें',
    role2Desc: 'अनुरोध बनाएं, उपयुक्त रक्तदाताओं को मिलाएं, और प्रतिक्रिया लाइव देखें।',
    role3Mark: 'ब्लड बैंक',
    role3Title: 'लाइव इन्वेंट्री प्रबंधित करें',
    role3Desc: 'रक्त इकाइयों पर नज़र रखें, आपूर्ति दबाव देखें, और अस्पतालों के बीच समन्वय करें।',
    role4Mark: 'प्रशासक',
    role4Title: 'पूरे नेटवर्क पर नज़र रखें',
    role4Desc: 'लाइव मीट्रिक्स और क्षेत्रीय गतिविधि से सिस्टम को सक्रिय रखें।',
    impactEyebrow: 'यह क्यों काम करता है',
    impactTitle: 'हर चरण में देरी कम करने के लिए बनाया गया।',
    impactDesc: 'BloodNet संगतता नियम, प्राथमिकता और स्पष्ट प्रक्रिया को जोड़ता है ताकि खोज में कम और कार्रवाई में अधिक समय लगे।',
    faqEyebrow: 'सामान्य प्रश्न',
    faqTitle: 'यह क्या है, क्यों उपयोगी है, और दूसरों से बेहतर क्यों है।',
    faq1Question: 'यह क्या है?',
    faq1Answer: 'BloodNet एक रक्तदाता नेटवर्क है जो अस्पताल, रक्तदाता और ब्लड बैंक को एक ही जगह जोड़ता है।',
    faq2Question: 'यह उपयोगी क्यों है?',
    faq2Answer: 'यह समय बचाता है, सही रक्तदाता जल्दी ढूँढता है, और आपात स्थिति में प्रतिक्रिया को तेज़ बनाता है।',
    faq3Question: 'यह दूसरों से बेहतर क्यों है?',
    faq3Answer: 'इसमें प्राथमिकता, दूरी, और उपलब्धता के आधार पर मिलान होता है, इसलिए खोज यादृच्छिक नहीं रहती।',
    faq4Question: 'क्या यह अस्पताल के लिए आसान है?',
    faq4Answer: 'हाँ, अस्पताल कुछ ही क्लिक में अनुरोध भेज सकता है और मिलान किए गए रक्तदाताओं को तुरंत सूचित कर सकता है।',
    faq5Question: 'क्या इससे वास्तविक मदद मिलती है?',
    faq5Answer: 'हाँ, तेज़ मिलान, स्पष्ट प्रक्रिया, और लाइव सूचनाओं के कारण सहायता समय पर पहुँचने की संभावना बढ़ती है।',
    footerBrandDesc: 'स्मार्ट रक्तदाता नेटवर्क',
    footerTeam: 'परियोजना टीम',
    team1: 'Angel Blessy (2547213)',
    team2: 'Enrita Fernandes (2547223)',
    footerLinks: 'त्वरित लिंक',
    footerLink1: 'विशेषताएँ',
    footerLink2: 'भूमिकाएँ',
    footerLink3: 'प्रभाव',
    legal1: 'MCA 2025–27 · CHRIST (Deemed to be University), Bangalore Central Campus',
    legal2: '© 2026 BloodNet',
    modalTitle: 'आपात अनुरोध भेजें',
    modalDesc: 'यह डेमो अस्पताल से रक्तदाता वर्कफ़्लो को दिखाता है।',
    fieldTitle: 'मरीज / अनुरोध शीर्षक',
    fieldTitlePlaceholder: 'उदा. दुर्घटना मरीज',
    fieldBloodGroup: 'रक्त समूह',
    fieldUnits: 'आवश्यक यूनिट',
    modalSubmit: 'मिले हुए रक्तदाताओं को सूचित करें',
    toastLanguage: 'भाषा हिंदी में सेट है।',
    toastNotify: 'शीर्ष 3 रक्तदाताओं को सफलतापूर्वक सूचित किया गया।',
    toastRequest: 'आपात अनुरोध बनाया गया। मिलान किए गए रक्तदाताओं को सूचित किया जा रहा है।',
    ariaClose: 'अनुरोध फ़ॉर्म बंद करें',
    notifyPopupKicker: 'सूचना',
    notifyPopupTitle: 'रक्तदाताओं को सूचित किया गया',
    notifyPopupDesc: 'वर्तमान अनुरोध के लिए शीर्ष मिलान किए गए रक्तदाताओं को सूचित कर दिया गया है।'
  },
  ta: {
    pageTitle: 'BloodNet - நவீன இரத்ததானி வலைப்பின்னல்',
    brandTag: 'நவீன இரத்ததானி வலைப்பின்னல்',
    langLabel: 'மொழி',
    headerExplore: 'பங்குகளைப் பாருங்கள்',
    headerRequest: 'கோரிக்கை அனுப்பவும்',
    heroPill: 'AI இயக்கம் · உடனடி',
    heroTitle: 'ஒவ்வொரு நொடியும் முக்கியம். ஒவ்வொரு தானியரும் முக்கியம்.',
    heroDesc: 'தானியர்கள், மருத்துவமனைகள், மற்றும் ரத்த வங்கிகளை இணைக்கும் AI வலைப்பின்னல்; சரியான தானியரை சில நொடிகளில் கண்டுபிடிக்கிறது.',
    ctaPrimary: 'தானியராகுங்கள்',
    ctaSecondary: 'இது எப்படி வேலை செய்கிறது',
    statDonors: 'செயலில் உள்ள தானியர்கள்',
    statHospitals: 'கூட்டணி மருத்துவமனைகள்',
    statLives: 'பாதிக்கப்பட்ட உயிர்கள்',
    statResponse: 'சராசரி பதில்',
    criticalTag: 'அவசர கோரிக்கை · 2 நிமிடங்களுக்கு முன்',
    liveTag: 'நேரலை',
    liveTitle: 'செயின்ட் மார்த்தா மருத்துவமனை · O+ ரத்தம்',
    liveDesc: '2 யூனிட்கள் · 3.2 கி.மீ தூரம்',
    notifyTop: 'முதன்மை தானியர்களுக்கு அறிவிக்கவும்',
    featuresEyebrow: 'உயிர்க்கும் நேரங்களுக்காக உருவாக்கப்பட்டது',
    featuresTitle: 'கைமுறை குழப்பத்தை ஒருங்கிணைந்த பதிலாக மாற்றும் திறன்கள்.',
    feature1Title: 'அவசர எச்சரிக்கைகள்',
    feature1Desc: 'கோரிக்கை எழுந்த உடனே மேலிட தானியர்களுக்கு அறிவிப்பு செல்கிறது.',
    feature2Title: 'கிடைக்கும் வாய்ப்பு கணிப்பு',
    feature2Desc: 'இப்போது யார் பதிலளிக்கலாம் என்பதை மதிப்பிட உதவுகிறது.',
    feature3Title: 'முன்னுரிமை தரவரிசை',
    feature3Desc: 'தூரம், சமீபத்தன்மை, பதில் வரலாறு, மற்றும் AI சிக்னல் அடிப்படையில்.',
    feature4Title: 'வரலாறு மற்றும் பேட்ஜ்கள்',
    feature4Desc: 'தான புள்ளிகள், சான்றிதழ்கள், மற்றும் தொடர்ச்சியான தானியர்களுக்கான அங்கீகாரம்.',
    feature5Title: 'வரைபட தேடல்',
    feature5Desc: 'உகந்த தானியர்களை சுற்றளவில் கண்டுபிடித்து தொடர்புடையவர்களை மேலே காட்டுகிறது.',
    feature6Title: 'நிர்வாக பகுப்பாய்வு',
    feature6Desc: 'தேவை, நிறைவேற்ற வேகம், மற்றும் தானியர் நிலைத்தன்மையை ஒரே டாஷ்போர்டில் பார்க்கலாம்.',
    rolesEyebrow: 'ஒரே தளம் · நான்கு பங்குகள்',
    rolesTitle: 'ஒவ்வொரு பயனருக்கும் அவர்களின் பங்குக்கு ஏற்ப சிறப்பு அனுபவம் கிடைக்கும்.',
    role1Mark: 'தானியர்',
    role1Title: 'எச்சரிக்கைகள் பெற்று தாக்கத்தைப் பின்தொடரவும்',
    role1Desc: 'பொருந்திய கோரிக்கைகளைப் பார்த்து, விரைவாக பதிலளித்து, உங்கள் தான வரலாற்றைப் பாருங்கள்.',
    role2Mark: 'மருத்துவமனை',
    role2Title: 'அவசர கோரிக்கைகளை உடனே அனுப்புங்கள்',
    role2Desc: 'கோரிக்கை உருவாக்கி, தகுதியான தானியர்களை பொருத்தி, நேரலையில் பதிலைப் பின்தொடருங்கள்.',
    role3Mark: 'ரத்த வங்கி',
    role3Title: 'நேரடி கையிருப்பை நிர்வகிக்கவும்',
    role3Desc: 'ரத்த யூனிட்களை கண்காணித்து, வழங்கல் அழுத்தத்தைக் கண்டு, மருத்துவமனைகளுடன் ஒருங்கிணைக்கவும்.',
    role4Mark: 'நிர்வாகி',
    role4Title: 'முழு வலைப்பின்னலைப் பாருங்கள்',
    role4Desc: 'நேரடி அளவுகள், தானியர் ஈடுபாடு, மற்றும் பிராந்திய செயல்பாட்டை பயன்படுத்தி அமைப்பை செயலில் வைத்திருங்கள்.',
    impactEyebrow: 'ஏன் இது வேலை செய்கிறது',
    impactTitle: 'ஒவ்வொரு படியிலும் தாமதத்தை குறைக்க வடிவமைக்கப்பட்டது.',
    impactDesc: 'BloodNet பொருந்தும் விதிகள், தரவரிசை பரிந்துரைகள், மற்றும் தெளிவான பதில் ஓட்டத்தை இணைக்கிறது.',
    faqEyebrow: 'அடிக்கடி கேட்கப்படும் கேள்விகள்',
    faqTitle: 'இது என்ன, ஏன் பயனுள்ளது, மற்றும் ஏன் வேறுபடுகிறது.',
    faq1Question: 'இது என்ன?',
    faq1Answer: 'BloodNet என்பது மருத்துவமனைகள், தானியர்கள், மற்றும் ரத்த வங்கிகளை ஒரே இடத்தில் இணைக்கும் வலைப்பின்னல்.',
    faq2Question: 'ஏன் பயனுள்ளது?',
    faq2Answer: 'இது நேரத்தைச் சேமித்து, சரியான தானியரை வேகமாகக் கண்டுபிடித்து, அவசரத்தில் பதிலை வேகப்படுத்துகிறது.',
    faq3Question: 'மற்றவற்றைவிட ஏன் சிறப்பு?',
    faq3Answer: 'முன்னுரிமை, தூரம், மற்றும் கிடைப்பின் அடிப்படையில் பொருத்துகிறது; தேடல் சீரற்றது அல்ல.',
    faq4Question: 'மருத்துவமனைகளுக்கு எளிதா?',
    faq4Answer: 'ஆம், சில கிளிக்குகளில் கோரிக்கை எழுப்பி பொருந்திய தானியர்களுக்கு உடனே அறிவிக்கலாம்.',
    faq5Question: 'உண்மையில் உதவுமா?',
    faq5Answer: 'ஆம், வேகமான பொருத்தம், தெளிவான நடைமுறை, மற்றும் நேரடி அறிவிப்புகள் நேரத்தில் உதவி கிடைக்கும் வாய்ப்பை உயர்த்தும்.',
    footerBrandDesc: 'நவீன இரத்ததானி வலைப்பின்னல்',
    footerTeam: 'திட்ட குழு',
    team1: 'Angel Blessy (2547213)',
    team2: 'Enrita Fernandes (2547223)',
    footerLinks: 'விரைவு இணைப்புகள்',
    footerLink1: 'அம்சங்கள்',
    footerLink2: 'பங்குகள்',
    footerLink3: 'தாக்கம்',
    legal1: 'MCA 2025–27 · CHRIST (Deemed to be University), Bangalore Central Campus',
    legal2: '© 2026 BloodNet',
    modalTitle: 'அவசர கோரிக்கை அனுப்பவும்',
    modalDesc: 'இந்த டெமோ மருத்துவமனை-தானியர் வேலைப்பாட்டை காட்டுகிறது.',
    fieldTitle: 'நோயாளர் / கோரிக்கை தலைப்பு',
    fieldTitlePlaceholder: 'உதா. விபத்து நோயாளர்',
    fieldBloodGroup: 'இரத்த வகை',
    fieldUnits: 'தேவையான யூனிட்கள்',
    modalSubmit: 'பொருந்திய தானியர்களுக்கு அறிவிக்கவும்',
    toastLanguage: 'மொழி தமிழுக்கு மாற்றப்பட்டது.',
    toastNotify: 'முதல் 3 பொருந்திய தானியர்களுக்கு அறிவிக்கப்பட்டது.',
    toastRequest: 'அவசர கோரிக்கை உருவாக்கப்பட்டது. பொருந்திய தானியர்களுக்கு அறிவிக்கப்படுகிறது.',
    ariaClose: 'கோரிக்கை படிவத்தை மூடு',
    notifyPopupKicker: 'அறிவிப்பு',
    notifyPopupTitle: 'தானியர்களுக்கு அறிவிக்கப்பட்டது',
    notifyPopupDesc: 'தற்போதைய கோரிக்கைக்காக மேலிட பொருந்திய தானியர்கள் அறிவிக்கப்பட்டுள்ளனர்.'
  },
  te: {
    pageTitle: 'BloodNet - స్మార్ట్ రక్తదాత నెట్‌వర్క్',
    brandTag: 'స్మార్ట్ రక్తదాత నెట్‌వర్క్',
    langLabel: 'భాష',
    headerExplore: 'పాత్రలు చూడండి',
    headerRequest: 'అభ్యర్థన పంపండి',
    heroPill: 'AI ఆధారితం · తక్షణం',
    heroTitle: 'ప్రతి సెకను ముఖ్యం. ప్రతి దాత ముఖ్యం.',
    heroDesc: 'దాతలు, ఆసుపత్రులు, మరియు రక్త బ్యాంకులను కలిపే AI నెట్‌వర్క్; సరైన దాతను క్షణాల్లో కనుగొంటుంది.',
    ctaPrimary: 'దాతగా మారండి',
    ctaSecondary: 'ఇది ఎలా పనిచేస్తుంది',
    statDonors: 'క్రియాశీల దాతలు',
    statHospitals: 'భాగస్వామ్య ఆసుపత్రులు',
    statLives: 'ప్రభావిత జీవితాలు',
    statResponse: 'సగటు స్పందన',
    criticalTag: 'అత్యవసర అభ్యర్థన · 2 నిమిషాల క్రితం',
    liveTag: 'ప్రత్యక్షం',
    liveTitle: 'సెంట్ మార్థా హాస్పిటల్ · O+ రక్తం',
    liveDesc: '2 యూనిట్లు · 3.2 కి.మీ దూరం',
    notifyTop: 'టాప్ దాతలకు తెలియజేయండి',
    featuresEyebrow: 'ప్రాణాపాయ క్షణాల కోసం రూపొందించబడింది',
    featuresTitle: 'మాన్యువల్ హడావుడిని సమన్వయిత స్పందనగా మార్చే సామర్థ్యాలు.',
    feature1Title: 'అత్యవసర హెచ్చరికలు',
    feature1Desc: 'అభ్యర్థన వచ్చిన వెంటనే టాప్ ర్యాంక్ దాతలకు నోటిఫికేషన్ పంపుతుంది.',
    feature2Title: 'లభ్యత అంచనా',
    feature2Desc: 'ఇప్పుడు ఎవరు స్పందించే అవకాశం ఉందో అంచనా వేయడానికి సహాయపడుతుంది.',
    feature3Title: 'ప్రాధాన్యత ర్యాంకింగ్',
    feature3Desc: 'దూరం, తాజాదనం, స్పందన చరిత్ర, మరియు AI సంకేతం ఆధారంగా.',
    feature4Title: 'చరిత్ర & బ్యాడ్జులు',
    feature4Desc: 'దాన మైలురాళ్లు, సర్టిఫికెట్లు, మరియు క్రమం తప్పని దాతలకు గుర్తింపు.',
    feature5Title: 'మ్యాప్ శోధన',
    feature5Desc: 'అనుకూల దాతలను పరిధిలో కనుగొని సంబంధిత వారిని పైకి చూపుతుంది.',
    feature6Title: 'అడ్మిన్ విశ్లేషణలు',
    feature6Desc: 'డిమాండ్, ఫుల్ఫిల్‌మెంట్ వేగం, మరియు దాత నిలకడను ఒకే డాష్‌బోర్డ్‌లో చూడండి.',
    rolesEyebrow: 'ఒక ప్లాట్‌ఫాం · నాలుగు పాత్రలు',
    rolesTitle: 'ప్రతి వినియోగదారునికి వారి పాత్రకు తగిన కేంద్రీకృత అనుభవం లభిస్తుంది.',
    role1Mark: 'దాత',
    role1Title: 'హెచ్చరికలు పొందండి మరియు ప్రభావాన్ని చూడండి',
    role1Desc: 'సరిపోలిన అభ్యర్థనలను చూడండి, వేగంగా స్పందించండి, మరియు మీ దాన చరిత్రను చూసుకోండి.',
    role2Mark: 'ఆసుపత్రి',
    role2Title: 'అత్యవసర అభ్యర్థనలను వెంటనే పంపండి',
    role2Desc: 'అభ్యర్థన సృష్టించి, అర్హులైన దాతలను సరిపోల్చి, ప్రత్యక్షంగా స్పందనను చూడండి.',
    role3Mark: 'రక్త బ్యాంక్',
    role3Title: 'ప్రత్యక్ష నిల్వను నిర్వహించండి',
    role3Desc: 'రక్త యూనిట్లను ట్రాక్ చేసి, సరఫరా ఒత్తిడిని చూసి, ఆసుపత్రులతో సమన్వయం చేయండి.',
    role4Mark: 'అడ్మిన్',
    role4Title: 'మొత్తం నెట్‌వర్క్‌ను చూడండి',
    role4Desc: 'ప్రత్యక్ష మెట్రిక్స్, నిలకడ, మరియు ప్రాంతీయ కార్యాచరణతో వ్యవస్థను స్పందనాత్మకంగా ఉంచండి.',
    impactEyebrow: 'ఇది ఎందుకు పని చేస్తుంది',
    impactTitle: 'ప్రతి దశలో ఆలస్యాన్ని తగ్గించడానికి రూపొందించబడింది.',
    impactDesc: 'BloodNet సరిపోలిక నియమాలు, ర్యాంక్ చేసిన సూచనలు, మరియు స్పష్టమైన స్పందన ప్రవాహాన్ని కలుపుతుంది.',
    faqEyebrow: 'తరచుగా అడిగే ప్రశ్నలు',
    faqTitle: 'ఇది ఏమిటి, ఎందుకు ఉపయోగం, మరియు ఎందుకు ప్రత్యేకం.',
    faq1Question: 'ఇది ఏమిటి?',
    faq1Answer: 'BloodNet అనేది ఆసుపత్రులు, దాతలు, మరియు రక్త బ్యాంకులను ఒకచోట కలిపే నెట్‌వర్క్.',
    faq2Question: 'ఇది ఎందుకు ఉపయోగం?',
    faq2Answer: 'ఇది సమయాన్ని ఆదా చేసి, సరైన దాతను త్వరగా కనుగొని, అత్యవసరాలలో స్పందనను వేగవంతం చేస్తుంది.',
    faq3Question: 'ఇతరుల కంటే ఎందుకు బెటర్?',
    faq3Answer: 'ప్రాధాన్యత, దూరం, మరియు లభ్యత ఆధారంగా సరిపోల్చుతుంది; శోధన యాదృచ్ఛికం కాదు.',
    faq4Question: 'ఆసుపత్రులకు ఇది సులభమా?',
    faq4Answer: 'అవును, కొన్ని క్లిక్‌లలో అభ్యర్థన పంపి సరిపోలిన దాతలకు వెంటనే తెలియజేయొచ్చు.',
    faq5Question: 'నిజంగా ఉపయోగపడుతుందా?',
    faq5Answer: 'అవును, వేగవంతమైన సరిపోలిక, స్పష్టమైన ప్రక్రియ, మరియు ప్రత్యక్ష నోటిఫికేషన్లు సహాయం సమయానికి చేరే అవకాశాన్ని పెంచుతాయి.',
    footerBrandDesc: 'స్మార్ట్ రక్తదాత నెట్‌వర్క్',
    footerTeam: 'ప్రాజెక్ట్ టీం',
    team1: 'Angel Blessy (2547213)',
    team2: 'Enrita Fernandes (2547223)',
    footerLinks: 'త్వరిత లింకులు',
    footerLink1: 'ఫీచర్లు',
    footerLink2: 'పాత్రలు',
    footerLink3: 'ప్రభావం',
    legal1: 'MCA 2025–27 · CHRIST (Deemed to be University), Bangalore Central Campus',
    legal2: '© 2026 BloodNet',
    modalTitle: 'అత్యవసర అభ్యర్థన పంపండి',
    modalDesc: 'ఈ డెమో ఆసుపత్రి-దాత వర్క్‌ఫ్లోను చూపిస్తుంది.',
    fieldTitle: 'రోగి / అభ్యర్థన శీర్షిక',
    fieldTitlePlaceholder: 'ఉదా. ప్రమాద రోగి',
    fieldBloodGroup: 'రక్త గ్రూప్',
    fieldUnits: 'అవసరమైన యూనిట్లు',
    modalSubmit: 'సరిపోలిన దాతలకు తెలియజేయండి',
    toastLanguage: 'భాష తెలుగుకు మార్చబడింది.',
    toastNotify: 'మొదటి 3 సరిపోలిన దాతలకు విజయవంతంగా తెలియజేయబడింది.',
    toastRequest: 'అత్యవసర అభ్యర్థన సృష్టించబడింది. సరిపోలిన దాతలకు తెలియజేయబడుతోంది.',
    ariaClose: 'అభ్యర్థన ఫారమ్ మూసేయండి',
    notifyPopupKicker: 'నోటిఫికేషన్',
    notifyPopupTitle: 'దాతలకు తెలియజేయబడింది',
    notifyPopupDesc: 'ప్రస్తుత అభ్యర్థనకు టాప్ సరిపోలిన దాతలకు నోటిఫై చేయబడింది.'
  },
  kn: {
    pageTitle: 'BloodNet - ಸ್ಮಾರ್ಟ್ ರಕ್ತದಾನಿ ಜಾಲ',
    brandTag: 'ಸ್ಮಾರ್ಟ್ ರಕ್ತದಾನಿ ಜಾಲ',
    langLabel: 'ಭಾಷೆ',
    headerExplore: 'ಪಾತ್ರಗಳನ್ನು ನೋಡಿ',
    headerRequest: 'ಮನವಿ ಕಳುಹಿಸಿ',
    heroPill: 'AI ಚಾಲಿತ · ತಕ್ಷಣ',
    heroTitle: 'ಪ್ರತಿ ಸೆಕೆಂಡ್ ಮುಖ್ಯ. ಪ್ರತಿ ದಾನಿ ಮುಖ್ಯ.',
    heroDesc: 'ದಾನಿಗಳು, ಆಸ್ಪತ್ರೆಗಳು, ಮತ್ತು ರಕ್ತ ಬ್ಯಾಂಕ್‌ಗಳನ್ನು ಕನೆಕ್ಟ್ ಮಾಡುವ AI ಜಾಲ; ಸರಿಯಾದ ದಾನಿಯನ್ನು ಕ್ಷಣಗಳಲ್ಲಿ ಕಂಡುಹಿಡಿಯುತ್ತದೆ.',
    ctaPrimary: 'ದಾನಿಯಾಗಿರಿ',
    ctaSecondary: 'ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ',
    statDonors: 'ಸಕ್ರಿಯ ದಾನಿಗಳು',
    statHospitals: 'ಸಹಭಾಗಿತ್ವದ ಆಸ್ಪತ್ರೆಗಳು',
    statLives: 'ಪ್ರಭಾವಿತ ಜೀವಗಳು',
    statResponse: 'ಸರಾಸರಿ ಪ್ರತಿಕ್ರಿಯೆ',
    criticalTag: 'ತುರ್ತು ಮನವಿ · 2 ನಿಮಿಷಗಳ ಹಿಂದೆ',
    liveTag: 'ಲೈವ್',
    liveTitle: 'ಸೇಂಟ್ ಮಾರ್ಥಾ ಆಸ್ಪತ್ರೆ · O+ ರಕ್ತ',
    liveDesc: '2 ಯೂನಿಟ್ · 3.2 ಕಿಮೀ ದೂರ',
    notifyTop: 'ಮೇಲಿನ ದಾನಿಗಳಿಗೆ ತಿಳಿಸಿ',
    featuresEyebrow: 'ಜೀವನ-ಮರಣ ಕ್ಷಣಗಳಿಗಾಗಿ ನಿರ್ಮಿತ',
    featuresTitle: 'ಹಸ್ತಚಾಲಿತ ಗೊಂದಲವನ್ನು ಸಮನ್ವಯಿತ ಪ್ರತಿಕ್ರಿಯೆಯಾಗಿ ಮಾಡುವ ಸಾಮರ್ಥ್ಯಗಳು.',
    feature1Title: 'ತುರ್ತು ಎಚ್ಚರಿಕೆಗಳು',
    feature1Desc: 'ಮನವಿ ಬಂದ ತಕ್ಷಣ ಟಾಪ್ ದಾನಿಗಳಿಗೆ ನೋಟಿಫಿಕೇಶನ್ ಹೋಗುತ್ತದೆ.',
    feature2Title: 'ಲಭ್ಯತೆ ಅಂದಾಜು',
    feature2Desc: 'ಈಗ ಯಾರು ಪ್ರತಿಕ್ರಿಯಿಸಬಹುದು ಎಂಬುದನ್ನು ಅಂದಾಜಿಸಲು ಸಹಾಯಕ.',
    feature3Title: 'ಪ್ರಾಥಮಿಕತೆ ರ್ಯಾಂಕಿಂಗ್',
    feature3Desc: 'ದೂರ, ಇತ್ತೀಚಿನತೆ, ಪ್ರತಿಕ್ರಿಯೆ ಇತಿಹಾಸ, ಮತ್ತು AI ಸಂಕೇತ ಆಧಾರದಲ್ಲಿ.',
    feature4Title: 'ಇತಿಹಾಸ ಮತ್ತು ಬ್ಯಾಡ್ಜ್‌ಗಳು',
    feature4Desc: 'ದಾನ ಮೈಲಿಗಲ್ಲುಗಳು, ಪ್ರಮಾಣಪತ್ರಗಳು, ಮತ್ತು ನಿಯಮಿತ ದಾನಿಗಳಿಗೆ ಗುರುತింపు.',
    feature5Title: 'ಮ್ಯಾಪ್ ಹುಡುಕು',
    feature5Desc: 'ಅನುಕೂಲ ದಾನಿಗಳನ್ನು ವ್ಯಾಪ್ತಿಯಲ್ಲಿ ಹುಡುಕಿ, ಸಂಬಂಧಿತವರನ್ನು ಮೊದಲಿಗೆ ತೋರಿಸುತ್ತದೆ.',
    feature6Title: 'ಅಡ್ಮಿನ್ ಅನಾಲಿಟಿಕ್ಸ್',
    feature6Desc: 'ಬೇಡಿಕೆ, ಪೂರ್ಣಗೊಳಿಸುವ ವೇಗ, ಮತ್ತು ದಾನಿ ಉಳಿಕೆಗಳನ್ನು ಒಂದೇ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ನಲ್ಲಿ ನೋಡಿ.',
    rolesEyebrow: 'ಒಂದು ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ · ನಾಲ್ಕು ಪಾತ್ರಗಳು',
    rolesTitle: 'ಪ್ರತಿ ಬಳಕೆದಾರನಿಗೂ ಅವರ ಪಾತ್ರಕ್ಕೆ ತಕ್ಕ ಕೇಂದ್ರೀಕೃತ ಅನುಭವ ಸಿಗುತ್ತದೆ.',
    role1Mark: 'ದಾನಿ',
    role1Title: 'ಎಚ್ಚರಿಕೆಗಳನ್ನು ಪಡೆದು ಪರಿಣಾಮವನ್ನು ನೋಡಿ',
    role1Desc: 'ಹೊಂದಿಕೊಂಡ ಮನವಿಗಳನ್ನು ನೋಡಿ, ಬೇಗ ಪ್ರತಿಕ್ರಿಯಿಸಿ, ಮತ್ತು ದಾನ ಇತಿಹಾಸವನ್ನು ನೋಡಿ.',
    role2Mark: 'ಆಸ್ಪತ್ರೆ',
    role2Title: 'ತುರ್ತು ಮನವಿಗಳನ್ನು ತಕ್ಷಣ ಕಳುಹಿಸಿ',
    role2Desc: 'ಮನವಿ ರಚಿಸಿ, ಅರ್ಹ ದಾನಿಗಳನ್ನು ಹೊಂದಿಸಿ, ಮತ್ತು ಪ್ರತಿಕ್ರಿಯೆಯನ್ನು ನೇರವಾಗಿ ನೋಡಿ.',
    role3Mark: 'ರಕ್ತ ಬ್ಯಾಂಕ್',
    role3Title: 'ಲೈವ್ ಇನ್‌ವೆಂಟರಿ ನಿರ್ವಹಿಸಿ',
    role3Desc: 'ರಕ್ತ ಯೂನಿಟ್‌ಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ, ಸರಬರಾಜು ಒತ್ತಡ ನೋಡಿ, ಮತ್ತು ಆಸ್ಪತ್ರೆಗಳೊಂದಿಗೆ ಸಂಯೋಜಿಸಿ.',
    role4Mark: 'ಅಡ್ಮಿನ್',
    role4Title: 'ಪೂರ್ಣ ಜಾಲವನ್ನು ನೋಡಿ',
    role4Desc: 'ಲೈವ್ ಮೆಟ್ರಿಕ್ಸ್, ಉಳಿಕೆ ಒಳನೋಟಗಳು, ಮತ್ತು ಪ್ರಾದೇಶಿಕ ಚಟುವಟಿಕೆಯಿಂದ ವ್ಯವಸ್ಥೆಯನ್ನು ಚುರುಕಾಗಿ ಇಡಿ.',
    impactEyebrow: 'ಇದು ಏಕೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ',
    impactTitle: 'ಪ್ರತಿ ಹಂತದಲ್ಲೂ ವಿಳಂಬ ಕಡಿಮೆ ಮಾಡಲು ರೂಪಿಸಲಾಗಿದೆ.',
    impactDesc: 'BloodNet ಹೊಂದಾಣಿಕೆ ನಿಯಮಗಳು, ರ್ಯಾಂಕ್ ಶಿಫಾರಸುಗಳು, ಮತ್ತು ಸ್ಪಷ್ಟ ಪ್ರತಿಕ್ರಿಯೆ ಕೆಲಸವೇಳೆಯನ್ನು ಸೇರಿಸುತ್ತದೆ.',
    faqEyebrow: 'ಪದೇಪದೇ ಕೇಳುವ ಪ್ರಶ್ನೆಗಳು',
    faqTitle: 'ಇದು ಏನು, ಏಕೆ ಉಪಯುಕ್ತ, ಮತ್ತು ಏಕೆ ವಿಭಿನ್ನ.',
    faq1Question: 'ಇದು ಏನು?',
    faq1Answer: 'BloodNet ಆಸ್ಪತ್ರೆಗಳು, ದಾನಿಗಳು, ಮತ್ತು ರಕ್ತ ಬ್ಯಾಂಕ್‌ಗಳನ್ನು ಒಂದೇ ಸ್ಥಳದಲ್ಲಿ ಸಂಪರ್ಕಿಸುವ ಜಾಲ.',
    faq2Question: 'ಇದು ಏಕೆ ಉಪಯುಕ್ತ?',
    faq2Answer: 'ಇದು ಸಮಯ ಉಳಿಸಿ, ಸರಿಯಾದ ದಾನಿಯನ್ನು ಬೇಗ ಹುಡುಕಿ, ತುರ್ತು ಸಂದರ್ಭಗಳಲ್ಲಿ ಪ್ರತಿಕ್ರಿಯೆಯನ್ನು ವೇಗಗೊಳಿಸುತ್ತದೆ.',
    faq3Question: 'ಇತರಕ್ಕಿಂತ ಏಕೆ ಉತ್ತಮ?',
    faq3Answer: 'ಪ್ರಾಥಮಿಕತೆ, ದೂರ, ಮತ್ತು ಲಭ್ಯತೆ ಆಧರಿಸಿ ಹೊಂದಾಣಿಕೆ ಮಾಡುತ್ತದೆ; ಹುಡುಕಾಟ ಯಾದೃಚ್ಛಿಕವಲ್ಲ.',
    faq4Question: 'ಆಸ್ಪತ್ರೆಗಳಿಗೆ ಇದು ಸುಲಭವೇ?',
    faq4Answer: 'ಹೌದು, ಕೆಲವೇ ಕ್ಲಿಕ್‌ಗಳಲ್ಲಿ ಮನವಿ ಮಾಡಿ ಹೊಂದಿದ ದಾನಿಗಳಿಗೆ ತಕ್ಷಣ ತಿಳಿಸಬಹುದು.',
    faq5Question: 'ನಿಜವಾಗಿಯೂ ಸಹಾಯವಾಗುತ್ತದೆಯೇ?',
    faq5Answer: 'ಹೌದು, ವೇಗವಾದ ಹೊಂದಾಣಿಕೆ, ಸ್ಪಷ್ಟ ಪ್ರಕ್ರಿಯೆ, ಮತ್ತು ನೇರ ಸೂಚನೆಗಳು ಸಹಾಯ ಸಮಯಕ್ಕೆ ತಲುಪುವ ಸಾಧ್ಯತೆಯನ್ನು ಹೆಚ್ಚಿಸುತ್ತವೆ.',
    footerBrandDesc: 'ಸ್ಮಾರ್ಟ್ ರಕ್ತದಾನಿ ಜಾಲ',
    footerTeam: 'ಪ್ರಾಜೆಕ್ಟ್ ತಂಡ',
    team1: 'Angel Blessy (2547213)',
    team2: 'Enrita Fernandes (2547223)',
    footerLinks: 'ತ್ವರಿತ ಲಿಂಕ್‌ಗಳು',
    footerLink1: 'ಅಮ್ಸ್',
    footerLink2: 'ಪಾತ್ರಗಳು',
    footerLink3: 'ಪ್ರಭಾವ',
    legal1: 'MCA 2025–27 · CHRIST (Deemed to be University), Bangalore Central Campus',
    legal2: '© 2026 BloodNet',
    modalTitle: 'ತುರ್ತು ಮನವಿ ಕಳುಹಿಸಿ',
    modalDesc: 'ಈ ಡೆಮೊ ಆಸ್ಪತ್ರೆ-ದಾನಿ ಕೆಲಸವೇಳೆಯನ್ನು ತೋರಿಸುತ್ತದೆ.',
    fieldTitle: 'ರೋಗಿ / ಮನವಿ ಶೀರ್ಷಿಕೆ',
    fieldTitlePlaceholder: 'ಉದಾ. ಅಪಘಾತ ರೋಗಿ',
    fieldBloodGroup: 'ರಕ್ತ ಗುಂಪು',
    fieldUnits: 'ಅವಶ್ಯಕ ಯೂನಿಟ್‌ಗಳು',
    modalSubmit: 'ಹೊಂದಿದ ದಾನಿಗಳಿಗೆ ತಿಳಿಸಿ',
    toastLanguage: 'ಭಾಷೆ ಕನ್ನಡಕ್ಕೆ ಬದಲಾಯಿಸಲಾಗಿದೆ.',
    toastNotify: 'ಮೊದಲ 3 ಹೊಂದಿದ ದಾನಿಗಳಿಗೆ ಯಶಸ್ವಿಯಾಗಿ ತಿಳಿಸಲಾಗಿದೆ.',
    toastRequest: 'ತುರ್ತು ಮನವಿ ಸೃಷ್ಟಿಸಲಾಗಿದೆ. ಹೊಂದಿದ ದಾನಿಗಳಿಗೆ ತಿಳಿಸಲಾಗುತ್ತಿದೆ.',
    ariaClose: 'ಮನವಿ ಫಾರ್ಮ್ ಮುಚ್ಚಿ',
    notifyPopupKicker: 'ಸೂಚನೆ',
    notifyPopupTitle: 'ದಾನಿಗಳಿಗೆ ತಿಳಿಸಲಾಗಿದೆ',
    notifyPopupDesc: 'ಪ್ರಸ್ತುತ ಮನವಿಗೆ ಮೇಲಿನ ಹೊಂದಿದ ದಾನಿಗಳಿಗೆ ತಿಳಿಸಲಾಗಿದೆ.'
  },
  ml: {
    pageTitle: 'BloodNet - സ്മാർട്ട് രക്തദാതാ നെറ്റ്‌വർക്ക്',
    brandTag: 'സ്മാർട്ട് രക്തദാതാ നെറ്റ്‌വർക്ക്',
    langLabel: 'ഭാഷ',
    headerExplore: 'പങ്കുകൾ കാണുക',
    headerRequest: 'അഭ്യർത്ഥന അയക്കുക',
    heroPill: 'AI നയിച്ചത് · ഉടൻ',
    heroTitle: 'ഓരോ സെക്കൻഡും പ്രധാനമാണ്. ഓരോ ദാതാവും പ്രധാനമാണ്.',
    heroDesc: 'ദാതാക്കളെയും ആശുപത്രികളെയും രക്തബാങ്കുകളെയും ബന്ധിപ്പിക്കുന്ന AI നെറ്റ്‌വർക്ക്; ശരിയായ ദാതാവിനെ ചില സെക്കൻഡുകളിൽ കണ്ടെത്തുന്നു.',
    ctaPrimary: 'ദാതാവാകുക',
    ctaSecondary: 'ഇത് എങ്ങനെ പ്രവർത്തിക്കുന്നു',
    statDonors: 'സജീവ ദാതാക്കൾ',
    statHospitals: 'പങ്കാളി ആശുപത്രികൾ',
    statLives: 'ബാധിച്ച ജീവികൾ',
    statResponse: 'ശരാശരി പ്രതികരണം',
    criticalTag: 'അത്യാവശ്യ അഭ്യർത്ഥന · 2 മിനിറ്റ് മുമ്പ്',
    liveTag: 'ലൈവ്',
    liveTitle: 'സെന്റ് മാർത്താസ് ഹോസ്പിറ്റൽ · O+ രക്തം',
    liveDesc: '2 യൂണിറ്റ് · 3.2 കി.മി അകലെ',
    notifyTop: 'മുൻനിര ദാതാക്കളെ അറിയിക്കുക',
    featuresEyebrow: 'ജീവൻ-മരണം നിമിഷങ്ങൾക്കായി നിർമ്മിച്ചത്',
    featuresTitle: 'കൈമുറി തിരക്കിനെ ഏകോപിത പ്രതികരണമായി മാറ്റുന്ന കഴിവുകൾ.',
    feature1Title: 'അത്യാവശ്യ അലർട്ടുകൾ',
    feature1Desc: 'അഭ്യർത്ഥന ഉയർന്ന ഉടൻ ടോപ്പ് ദാതാക്കൾക്ക് അറിയിപ്പ് പോകും.',
    feature2Title: 'ലഭ്യത പ്രവചനം',
    feature2Desc: 'ഇപ്പോൾ ആരാണ് പ്രതികരിക്കാനിടയുള്ളത് എന്ന് വിലയിരുത്താൻ സഹായിക്കുന്നു.',
    feature3Title: 'പ്രാധാന്യ റാങ്കിംഗ്',
    feature3Desc: 'ദൂരം, പുതുമ, പ്രതികരണ ചരിത്രം, AI സിഗ്നൽ എന്നിവയെ അടിസ്ഥാനമാക്കി.',
    feature4Title: 'ചരിത്രവും ബാഡ്ജുകളും',
    feature4Desc: 'ദാന നേട്ടങ്ങൾ, സർട്ടിഫിക്കേറ്റുകൾ, സ്ഥിരദാതാക്കൾക്കുള്ള അംഗീകാരം.',
    feature5Title: 'മാപ്പ് തിരയൽ',
    feature5Desc: 'അനുയോജ്യ ദാതാക്കളെ പരിധിയിൽ കണ്ടെത്തി ബന്ധപ്പെട്ടവരെ മുമ്പിൽ കാണിക്കുന്നു.',
    feature6Title: 'അഡ്മിൻ അനലിറ്റിക്സ്',
    feature6Desc: 'ഡിമാൻഡ്, പൂർത്തീകരണ വേഗം, ദാതൃ നിലനിർത്തൽ എന്നിവ ഒരു ഡാഷ്ബോർഡിൽ കാണുക.',
    rolesEyebrow: 'ഒരു പ്ലാറ്റ്ഫോം · നാല് പങ്കുകൾ',
    rolesTitle: 'ഓരോ ഉപയോക്താവിനും അവരുടെ പങ്കിന് അനുയോജ്യമായ അനുഭവം ലഭിക്കും.',
    role1Mark: 'ദാതാവ്',
    role1Title: 'അലർട്ടുകൾ സ്വീകരിച്ച് സ്വാധീനം കാണുക',
    role1Desc: 'മാച്ച് ചെയ്ത അഭ്യർത്ഥനകൾ കാണുക, വേഗത്തിൽ പ്രതികരിക്കുക, നിങ്ങളുടെ ദാന ചരിത്രം സൂക്ഷിക്കുക.',
    role2Mark: 'ആശുപത്രി',
    role2Title: 'അത്യാവശ്യ അഭ്യർത്ഥനകൾ ഉടൻ അയയ്ക്കുക',
    role2Desc: 'അഭ്യർത്ഥന സൃഷ്ടിച്ച്, യോഗ്യ ദാതാക്കളെ മാച്ച് ചെയ്ത്, പ്രതികരണം തത്സമയം പിന്തുടരുക.',
    role3Mark: 'രക്തബാങ്ക്',
    role3Title: 'ലൈവ് ഇൻവെന്ററി കൈകാര്യം ചെയ്യുക',
    role3Desc: 'രക്ത യൂണിറ്റുകൾ പിന്തുടർന്ന്, വിതരണ സമ്മർദ്ദം നോക്കി, ആശുപത്രികളുമായി ഏകോപിപ്പിക്കുക.',
    role4Mark: 'അഡ്മിൻ',
    role4Title: 'മുഴുവൻ നെറ്റ്‌വർക്ക് കാണുക',
    role4Desc: 'ലൈവ് മീട്രിക്‌സ്, നിലനിർത്തൽ洞വിവരങ്ങൾ, പ്രാദേശിക പ്രവർത്തനം എന്നിവ ഉപയോഗിച്ച് സംവിധാനം പ്രതികരണക്ഷമമാക്കുക.',
    impactEyebrow: 'ഇത് എന്തുകൊണ്ട് പ്രവർത്തിക്കുന്നു',
    impactTitle: 'ഓരോ ഘട്ടത്തിലും വൈകിപ്പ് കുറയ്ക്കാൻ രൂപകൽപ്പന ചെയ്തത്.',
    impactDesc: 'BloodNet പൊരുത്ത നിയമങ്ങൾ, റാങ്ക് ചെയ്ത ശുപാർശകൾ, വ്യക്തമായ പ്രതികരണ പ്രവാഹം എന്നിവ ചേർക്കുന്നു.',
    faqEyebrow: 'പതിവ് ചോദ്യങ്ങൾ',
    faqTitle: 'ഇത് എന്ത്, എന്തുകൊണ്ട് ഉപകാരപ്രദം, എന്തുകൊണ്ട് വേറിട്ടത്.',
    faq1Question: 'ഇത് എന്താണ്?',
    faq1Answer: 'ആശുപത്രികൾ, ദാതാക്കൾ, രക്തബാങ്കുകൾ എന്നിവയെ ഒരിടത്ത് ബന്ധിപ്പിക്കുന്ന നെറ്റ്‌വർക്ക് ആണിത്.',
    faq2Question: 'ഇത് എന്തുകൊണ്ട് ഉപകാരപ്രദം?',
    faq2Answer: 'സമയം ലാഭിച്ച്, ശരിയായ ദാതാവിനെ വേഗത്തിൽ കണ്ടെത്തി, അടിയന്തര പ്രതികരണം വേഗമാക്കുന്നു.',
    faq3Question: 'മറ്റുള്ളവയെക്കാൾ എന്തുകൊണ്ട് മെച്ചം?',
    faq3Answer: 'പ്രാധാന്യം, ദൂരം, ലഭ്യത എന്നിവയെ അടിസ്ഥാനമാക്കി മാച്ച് ചെയ്യുന്നു; തിരയൽ യാദൃച്ഛികമല്ല.',
    faq4Question: 'ആശുപത്രികൾക്ക് ഇത് എളുപ്പമാണോ?',
    faq4Answer: 'അതെ, കുറച്ച് ക്ലിക്കുകളിൽ അഭ്യർത്ഥന നൽകി മാച്ച് ചെയ്ത ദാതാക്കളെ ഉടൻ അറിയിക്കാം.',
    faq5Question: 'യഥാർത്ഥത്തിൽ സഹായമുണ്ടോ?',
    faq5Answer: 'അതെ, വേഗത്തിലുള്ള മാച്ചിംഗ്, വ്യക്തമായ പ്രക്രിയ, തത്സമയ അറിയിപ്പുകൾ എന്നിവ സഹായം സമയത്ത് എത്താനുള്ള സാധ്യത ഉയർത്തുന്നു.',
    footerBrandDesc: 'സ്മാർട്ട് രക്തദാതാ നെറ്റ്‌വർക്ക്',
    footerTeam: 'പ്രോജക്ട് ടീം',
    team1: 'Angel Blessy (2547213)',
    team2: 'Enrita Fernandes (2547223)',
    footerLinks: 'ക്വിക്ക് ലിങ്കുകൾ',
    footerLink1: 'ഫീച്ചറുകൾ',
    footerLink2: 'പങ്കുകൾ',
    footerLink3: 'പ്രഭാവം',
    legal1: 'MCA 2025–27 · CHRIST (Deemed to be University), Bangalore Central Campus',
    legal2: '© 2026 BloodNet',
    modalTitle: 'അത്യാവശ്യ അഭ്യർത്ഥന അയക്കുക',
    modalDesc: 'ഈ ഡെമോ ആശുപത്രി-ദാതാവ് പ്രവാഹം കാണിക്കുന്നു.',
    fieldTitle: 'രോഗി / അഭ്യർത്ഥന ശീർഷകം',
    fieldTitlePlaceholder: 'ഉദാ. അപകട രോഗി',
    fieldBloodGroup: 'രക്ത ഗ്രൂപ്പ്',
    fieldUnits: 'ആവശ്യമായ യൂണിറ്റുകൾ',
    modalSubmit: 'മാച്ച് ചെയ്ത ദാതാക്കളെ അറിയിക്കുക',
    toastLanguage: 'ഭാഷ മലയാളത്തിലേക്ക് മാറ്റി.',
    toastNotify: 'മുൻനിര 3 മാച്ച് ചെയ്ത ദാതാക്കളെ വിജയകരമായി അറിയിച്ചു.',
    toastRequest: 'അത്യാവശ്യ അഭ്യർത്ഥന സൃഷ്ടിച്ചു. മാച്ച് ചെയ്ത ദാതാക്കളെ അറിയിക്കുന്നു.',
    ariaClose: 'അഭ്യർത്ഥന ഫോം അടയ്ക്കുക',
    notifyPopupKicker: 'അറിയിപ്പ്',
    notifyPopupTitle: 'ദാതാക്കളെ അറിയിച്ചു',
    notifyPopupDesc: 'നിലവിലെ അഭ്യർത്ഥനയ്ക്ക് മുകളിലുള്ള മാച്ച് ചെയ്ത ദാതാക്കളെ അറിയിച്ചു.'
  },
  or: {
    pageTitle: 'BloodNet - ସ୍ମାର୍ଟ ରକ୍ତଦାତା ନେଟୱର୍କ',
    brandTag: 'ସ୍ମାର୍ଟ ରକ୍ତଦାତା ନେଟୱର୍କ',
    langLabel: 'ଭାଷା',
    headerExplore: 'ଭୂମିକା ଦେଖନ୍ତୁ',
    headerRequest: 'ଅନୁରୋଧ ପଠାନ୍ତୁ',
    heroPill: 'AI ଚାଳିତ · ତୁରନ୍ତ',
    heroTitle: 'ପ୍ରତ୍ୟେକ ସେକେଣ୍ଡ ମୂଲ୍ୟବାନ। ପ୍ରତ୍ୟେକ ଦାତା ମୂଲ୍ୟବାନ।',
    heroDesc: 'ଦାତା, ହସ୍ପିଟାଲ ଏବଂ ବ୍ଲଡ ବ୍ୟାଙ୍କକୁ ଯୋଡୁଥିବା AI ନେଟୱର୍କ; ସଠିକ୍ ଦାତା କିଛି ସେକେଣ୍ଡରେ ମିଳେ।',
    ctaPrimary: 'ଦାତା ହୁଅନ୍ତୁ',
    ctaSecondary: 'ଏହା କିପରି କାମ କରେ',
    statDonors: 'ସକ୍ରିୟ ଦାତା',
    statHospitals: 'ସହଭାଗୀ ହସ୍ପିଟାଲ',
    statLives: 'ପ୍ରଭାବିତ ଜୀବନ',
    statResponse: 'ସାଧାରଣ ପ୍ରତିକ୍ରିୟା',
    criticalTag: 'ଜରୁରୀ ଅନୁରୋଧ · 2 ମିନିଟ ପୂର୍ବେ',
    liveTag: 'ଲାଇଭ୍',
    liveTitle: 'ସେଣ୍ଟ ମାର୍ଥା ହସ୍ପିଟାଲ · O+ ରକ୍ତ',
    liveDesc: '2 ଇଉନିଟ୍ · 3.2 କି.ମି. ଦୂରେ',
    notifyTop: 'ଶୀର୍ଷ ଦାତାଙ୍କୁ ସୂଚନା ଦିଅନ୍ତୁ',
    featuresEyebrow: 'ଜୀବନ-ମୃତ୍ୟୁ ମୁହୂର୍ତ୍ତ ପାଇଁ ତିଆରି',
    featuresTitle: 'ହାତେ ହୁଏଥିବା ହଡ଼ବଡ଼ିକୁ ସମନ୍ୱିତ ପ୍ରତିକ୍ରିୟାରେ ପରିଣତ କରୁଥିବା କ୍ଷମତା।',
    feature1Title: 'ଜରୁରୀ ସତର୍କବାଣୀ',
    feature1Desc: 'ଅନୁରୋଧ ଆସିଲେ ସାଥିସାଥି ଶୀର୍ଷ ଦାତାଙ୍କୁ ସୂଚନା ଯାଏ।',
    feature2Title: 'ଉପଲବ୍ଧତା ପୂର୍ବାନୁମାନ',
    feature2Desc: 'ଏବେ କିଏ ପ୍ରତିକ୍ରିୟା କରିପାରିବ ତାହା ଆନୁମାନ କରିବାରେ ସାହାଯ୍ୟ କରେ।',
    feature3Title: 'ପ୍ରାଥମିକତା ର୍ୟାଙ୍କିଂ',
    feature3Desc: 'ଦୂରତା, ସମ୍ପ୍ରତିକତା, ପ୍ରତିକ୍ରିୟା ଇତିହାସ ଏବଂ AI ସିଗ୍ନାଲ ଆଧାରିତ।',
    feature4Title: 'ଇତିହାସ ଏବଂ ବ୍ୟାଜ',
    feature4Desc: 'ଦାନ ମାଇଲସ୍ଟୋନ, ସର୍ଟିଫିକେଟ, ଏବଂ ନିୟମିତ ଦାତାଙ୍କ ପାଇଁ ସମ୍ମାନ।',
    feature5Title: 'ମ୍ୟାପ୍ ସନ୍ଧାନ',
    feature5Desc: 'ଉପଯୁକ୍ତ ଦାତାଙ୍କୁ ଅଞ୍ଚଳରେ ଖୋଜି ସମ୍ପର୍କିତଙ୍କୁ ଆଗରେ ରଖେ।',
    feature6Title: 'ପ୍ରଶାସନିକ ତଥ୍ୟାନୁଷ୍ଠାନ',
    feature6Desc: 'ଚାହିଦା, ପୂରଣ ଗତି, ଏବଂ ଦାତା ଧାରଣକୁ ଏକ ଡାଶବୋର୍ଡରେ ଦେଖନ୍ତୁ।',
    rolesEyebrow: 'ଏକ ପ୍ଲାଟଫର୍ମ · ଚାରି ଭୂମିକା',
    rolesTitle: 'ପ୍ରତ୍ୟେକ ବ୍ୟବହାରକାରୀଙ୍କୁ ତାଙ୍କ ଭୂମିକାଅନୁଯାୟୀ କେନ୍ଦ୍ରିତ ଅନୁଭବ ମିଳେ।',
    role1Mark: 'ଦାତା',
    role1Title: 'ସତର୍କବାଣୀ ପାଆନ୍ତୁ ଏବଂ ପ୍ରଭାବ ଦେଖନ୍ତୁ',
    role1Desc: 'ମେଳ ହୋଇଥିବା ଅନୁରୋଧ ଦେଖନ୍ତୁ, ଶୀଘ୍ର ପ୍ରତିକ୍ରିୟା ଦିଅନ୍ତୁ, ଏବଂ ଦାନ ଇତିହାସ ରଖନ୍ତୁ।',
    role2Mark: 'ହସ୍ପିଟାଲ',
    role2Title: 'ତୁରନ୍ତ ଜରୁରୀ ଅନୁରୋଧ ପଠାନ୍ତୁ',
    role2Desc: 'ଅନୁରୋଧ ତିଆରି କରି, ଯୋଗ୍ୟ ଦାତାଙ୍କୁ ମେଳ କରି, ପ୍ରତିକ୍ରିୟାକୁ ଲାଇଭ୍ ଦେଖନ୍ତୁ।',
    role3Mark: 'ବ୍ଲଡ ବ୍ୟାଙ୍କ',
    role3Title: 'ଲାଇଭ୍ ଇନ୍ଭେଣ୍ଟରି ନିୟନ୍ତ୍ରଣ କରନ୍ତୁ',
    role3Desc: 'ରକ୍ତ ଇଉନିଟ୍ ଟ୍ରାକ୍ କରନ୍ତୁ, ସରବରାହ ଚାପ ଦେଖନ୍ତୁ, ଏବଂ ହସ୍ପିଟାଲ ସହିତ ସମନ୍ୱୟ କରନ୍ତୁ।',
    role4Mark: 'ଅ୍ୟଡମିନ୍',
    role4Title: 'ସମଗ୍ର ନେଟୱର୍କ ଦେଖନ୍ତୁ',
    role4Desc: 'ଲାଇଭ୍ ମେଟ୍ରିକ୍ସ, ଧାରଣ ସୂଚନା, ଏବଂ ପ୍ରାନ୍ତୀୟ କାର୍ଯ୍ୟକଳାପ ସହିତ ସିଷ୍ଟମକୁ ସକ୍ରିୟ ରଖନ୍ତୁ।',
    impactEyebrow: 'ଏହା କାହିଁକି କାମ କରେ',
    impactTitle: 'ପ୍ରତ୍ୟେକ ପଦକ୍ଷେପରେ ବିଳମ୍ବ କମାଇବା ପାଇଁ ଡିଜାଇନ୍.',
    impactDesc: 'BloodNet ସମନ୍ୱୟ ନିୟମ, ର୍ୟାଙ୍କ ସୁପାରିଶ, ଏବଂ ସ୍ପଷ୍ଟ ପ୍ରତିକ୍ରିୟା ଧାରାକୁ ମିଶାଏ।',
    faqEyebrow: 'ସାଧାରଣ ପ୍ରଶ୍ନ',
    faqTitle: 'ଏହା କ’ଣ, କାହିଁକି ଉପଯୋଗୀ, ଏବଂ କାହିଁକି ଭିନ୍ନ.',
    faq1Question: 'ଏହା କ’ଣ?',
    faq1Answer: 'BloodNet ହେଉଛି ଏକ ନେଟୱର୍କ ଯାହା ହସ୍ପିଟାଲ, ଦାତା, ଏବଂ ବ୍ଲଡ ବ୍ୟାଙ୍କକୁ ଏକସାଥି କରେ।',
    faq2Question: 'ଏହା କାହିଁକି ଉପଯୋଗୀ?',
    faq2Answer: 'ଏହା ସମୟ ବଞ୍ଚାଏ, ସଠିକ୍ ଦାତାକୁ ଶୀଘ୍ର ମିଳାଏ, ଏବଂ ଜରୁରୀ ସମୟରେ ପ୍ରତିକ୍ରିୟା ଦ୍ରୁତ କରେ।',
    faq3Question: 'ଅନ୍ୟଠାରୁ କାହିଁକି ଭଲ?',
    faq3Answer: 'ପ୍ରାଥମିକତା, ଦୂରତା, ଏବଂ ଉପଲବ୍ଧତା ଆଧାରରେ ମେଳ କରେ, ତେଣୁ ସନ୍ଧାନ ସଂଯୋଗୀ ନୁହେଁ।',
    faq4Question: 'ହସ୍ପିଟାଲ ପାଇଁ ସହଜ କି?',
    faq4Answer: 'ହଁ, କିଛି କ୍ଲିକରେ ଅନୁରୋଧ ଦେଇ ମେଳ ହୋଇଥିବା ଦାତାଙ୍କୁ ତୁରନ୍ତ ଜଣାଇପାରିବେ।',
    faq5Question: 'ସତରେ ସାହାଯ୍ୟ କରେ କି?',
    faq5Answer: 'ହଁ, ଶୀଘ୍ର ମେଳ, ସ୍ପଷ୍ଟ ପ୍ରକ୍ରିୟା, ଏବଂ ଲାଇଭ୍ ନୋଟିଫିକେସନ୍ ସମୟରେ ସାହାଯ୍ୟ ପହଞ୍ଚିବା ସମ୍ଭାବନା ବଢ଼ାଏ।',
    footerBrandDesc: 'ସ୍ମାର୍ଟ ରକ୍ତଦାତା ନେଟୱର୍କ',
    footerTeam: 'ପ୍ରୋଜେକ୍ଟ ଟିମ୍',
    team1: 'Angel Blessy (2547213)',
    team2: 'Enrita Fernandes (2547223)',
    footerLinks: 'ତ୍ୱରିତ ଲିଙ୍କ',
    footerLink1: 'ବିଶେଷତା',
    footerLink2: 'ଭୂମିକା',
    footerLink3: 'ପ୍ରଭାବ',
    legal1: 'MCA 2025–27 · CHRIST (Deemed to be University), Bangalore Central Campus',
    legal2: '© 2026 BloodNet',
    modalTitle: 'ଜରୁରୀ ଅନୁରୋଧ ପଠାନ୍ତୁ',
    modalDesc: 'ଏହି ଡେମୋ ହସ୍ପିଟାଲ-ଦାତା କାର୍ଯ୍ୟପ୍ରବାହକୁ ଦେଖାଏ।',
    fieldTitle: 'ରୋଗୀ / ଅନୁରୋଧ ଶୀର୍ଷକ',
    fieldTitlePlaceholder: 'ଉଦା. ଦୁର୍ଘଟଣା ରୋଗୀ',
    fieldBloodGroup: 'ରକ୍ତ ଗୋଷ୍ଠୀ',
    fieldUnits: 'ଆବଶ୍ୟକ ଇଉନିଟ୍',
    modalSubmit: 'ମେଳ ହୋଇଥିବା ଦାତାଙ୍କୁ ଜଣାନ୍ତୁ',
    toastLanguage: 'ଭାଷା ଓଡ଼ିଆକୁ ବଦଳାଗଲା।',
    toastNotify: 'ଶୀର୍ଷ 3 ମେଳ ହୋଇଥିବା ଦାତାଙ୍କୁ ସଫଳତାର ସହିତ ଜଣାଗଲା।',
    toastRequest: 'ଜରୁରୀ ଅନୁରୋଧ ତିଆରି ହୋଇଛି। ମେଳ ହୋଇଥିବା ଦାତାଙ୍କୁ ଜଣାଯାଉଛି।',
    ariaClose: 'ଅନୁରୋଧ ଫର୍ମ ବନ୍ଦ କରନ୍ତୁ',
    notifyPopupKicker: 'ସୂଚନା',
    notifyPopupTitle: 'ଦାତାଙ୍କୁ ଜଣାଗଲା',
    notifyPopupDesc: 'ବର୍ତ୍ତମାନ ଅନୁରୋଧ ପାଇଁ ଶୀର୍ଷ ମେଳ ହୋଇଥିବା ଦାତାଙ୍କୁ ଜଣାଗଲା।'
  },
  bn: {
    pageTitle: 'BloodNet - স্মার্ট রক্তদাতা নেটওয়ার্ক',
    brandTag: 'স্মার্ট রক্তদাতা নেটওয়ার্ক',
    langLabel: 'ভাষা',
    headerExplore: 'ভূমিকা দেখুন',
    headerRequest: 'অনুরোধ পাঠান',
    heroPill: 'AI-চালিত · তাৎক্ষণিক',
    heroTitle: 'প্রতি সেকেন্ড গুরুত্বপূর্ণ। প্রতিটি দাতা গুরুত্বপূর্ণ।',
    heroDesc: 'দাতা, হাসপাতাল ও ব্লাড ব্যাংককে যুক্ত করা AI নেটওয়ার্ক; সঠিক দাতাকে কয়েক সেকেন্ডে খুঁজে পায়।',
    ctaPrimary: 'দাতা হন',
    ctaSecondary: 'এটি কীভাবে কাজ করে',
    statDonors: 'সক্রিয় দাতা',
    statHospitals: 'সহযোগী হাসপাতাল',
    statLives: 'প্রভাবিত জীবন',
    statResponse: 'গড় প্রতিক্রিয়া',
    criticalTag: 'জরুরি অনুরোধ · 2 মিনিট আগে',
    liveTag: 'লাইভ',
    liveTitle: 'সেন্ট মার্থা হাসপাতাল · O+ রক্ত',
    liveDesc: '2 ইউনিট · 3.2 কিমি দূরে',
    notifyTop: 'শীর্ষ দাতাদের জানান',
    featuresEyebrow: 'জীবন-মৃত্যুর মুহূর্তের জন্য তৈরি',
    featuresTitle: 'হাতের বিশৃঙ্খলাকে সমন্বিত প্রতিক্রিয়ায় বদলে দেওয়া ক্ষমতাগুলি।',
    feature1Title: 'জরুরি সতর্কতা',
    feature1Desc: 'অনুরোধ ওঠার সঙ্গে সঙ্গেই শীর্ষ দাতাদের কাছে নোটিফিকেশন যায়।',
    feature2Title: 'উপলব্ধতা পূর্বাভাস',
    feature2Desc: 'এখন কে সাড়া দিতে পারেন তা আন্দাজ করতে সাহায্য করে।',
    feature3Title: 'অগ্রাধিকার র‍্যাঙ্কিং',
    feature3Desc: 'দূরত্ব, সাম্প্রতিকতা, প্রতিক্রিয়া ইতিহাস, এবং AI সিগন্যালের ভিত্তিতে।',
    feature4Title: 'ইতিহাস ও ব্যাজ',
    feature4Desc: 'দান মাইলস্টোন, সার্টিফিকেট, এবং নিয়মিত দাতাদের স্বীকৃতি।',
    feature5Title: 'ম্যাপ অনুসন্ধান',
    feature5Desc: 'উপযুক্ত দাতাদের কাছাকাছি খুঁজে প্রাসঙ্গিকদের আগে দেখায়।',
    feature6Title: 'অ্যাডমিন অ্যানালিটিক্স',
    feature6Desc: 'চাহিদা, পূরণ গতি, এবং দাতা ধরে রাখা এক ড্যাশবোর্ডে দেখুন।',
    rolesEyebrow: 'এক প্ল্যাটফর্ম · চার ভূমিকা',
    rolesTitle: 'প্রতি ব্যবহারকারী তাদের ভূমিকা অনুযায়ী কেন্দ্রীভূত অভিজ্ঞতা পায়।',
    role1Mark: 'দাতা',
    role1Title: 'সতর্কতা পান এবং প্রভাব দেখুন',
    role1Desc: 'মিল পাওয়া অনুরোধ দেখুন, দ্রুত সাড়া দিন, এবং দানের ইতিহাস দেখুন।',
    role2Mark: 'হাসপাতাল',
    role2Title: 'তাৎক্ষণিক জরুরি অনুরোধ পাঠান',
    role2Desc: 'অনুরোধ তৈরি করে যোগ্য দাতাদের মিলিয়ে রিয়েল-টাইমে সাড়া দেখুন।',
    role3Mark: 'ব্লাড ব্যাংক',
    role3Title: 'লাইভ ইনভেন্টরি পরিচালনা করুন',
    role3Desc: 'রক্ত ইউনিট ট্র্যাক করুন, সরবরাহ চাপ দেখুন, এবং হাসপাতালের সাথে সমন্বয় করুন।',
    role4Mark: 'অ্যাডমিন',
    role4Title: 'পুরো নেটওয়ার্ক দেখুন',
    role4Desc: 'লাইভ মেট্রিক্স, ধরে রাখা, এবং আঞ্চলিক কার্যকলাপ দিয়ে সিস্টেম সচল রাখুন।',
    impactEyebrow: 'কেন এটি কাজ করে',
    impactTitle: 'প্রতিটি ধাপে দেরি কমানোর জন্য ডিজাইন করা।',
    impactDesc: 'BloodNet সামঞ্জস্য নিয়ম, র‍্যাঙ্ক করা সুপারিশ, এবং পরিষ্কার প্রতিক্রিয়া প্রবাহ একত্র করে।',
    faqEyebrow: 'সাধারণ প্রশ্ন',
    faqTitle: 'এটি কী, কেন উপকারী, এবং কেন আলাদা।',
    faq1Question: 'এটি কী?',
    faq1Answer: 'BloodNet এমন একটি নেটওয়ার্ক যা হাসপাতাল, দাতা, এবং ব্লাড ব্যাংককে এক জায়গায় যুক্ত করে।',
    faq2Question: 'এটি কেন উপকারী?',
    faq2Answer: 'এটি সময় বাঁচায়, সঠিক দাতাকে দ্রুত খুঁজে পায়, এবং জরুরিতে সাড়া দ্রুত করে।',
    faq3Question: 'অন্যদের তুলনায় কেন ভালো?',
    faq3Answer: 'অগ্রাধিকার, দূরত্ব, এবং উপলব্ধতার ভিত্তিতে মেলায়, তাই অনুসন্ধান এলোমেলো নয়।',
    faq4Question: 'হাসপাতালের জন্য সহজ?',
    faq4Answer: 'হ্যাঁ, কয়েক ক্লিকেই অনুরোধ করে মিল পাওয়া দাতাদের সাথে সাথে জানানো যায়।',
    faq5Question: 'আসলেই সাহায্য করে?',
    faq5Answer: 'হ্যাঁ, দ্রুত মেল, পরিষ্কার প্রক্রিয়া, এবং লাইভ নোটিফিকেশন সময়মতো সাহায্য পৌঁছানোর সম্ভাবনা বাড়ায়।',
    footerBrandDesc: 'স্মার্ট রক্তদাতা নেটওয়ার্ক',
    footerTeam: 'প্রকল্প দল',
    team1: 'Angel Blessy (2547213)',
    team2: 'Enrita Fernandes (2547223)',
    footerLinks: 'দ্রুত লিঙ্ক',
    footerLink1: 'বৈশিষ্ট্য',
    footerLink2: 'ভূমিকা',
    footerLink3: 'প্রভাব',
    legal1: 'MCA 2025–27 · CHRIST (Deemed to be University), Bangalore Central Campus',
    legal2: '© 2026 BloodNet',
    modalTitle: 'জরুরি অনুরোধ পাঠান',
    modalDesc: 'এই ডেমো হাসপাতাল-দাতা ওয়ার্কফ্লো দেখায়।',
    fieldTitle: 'রোগী / অনুরোধ শিরোনাম',
    fieldTitlePlaceholder: 'যেমন: দুর্ঘটনা রোগী',
    fieldBloodGroup: 'রক্তের গ্রুপ',
    fieldUnits: 'প্রয়োজনীয় ইউনিট',
    modalSubmit: 'মিল পাওয়া দাতাদের জানিয়ে দিন',
    toastLanguage: 'ভাষা বাংলায় বদলানো হয়েছে।',
    toastNotify: 'শীর্ষ 3 মিল পাওয়া দাতাদের সফলভাবে জানানো হয়েছে।',
    toastRequest: 'জরুরি অনুরোধ তৈরি হয়েছে। মিল পাওয়া দাতাদের জানানো হচ্ছে।',
    ariaClose: 'অনুরোধ ফর্ম বন্ধ করুন',
    notifyPopupKicker: 'নোটিফিকেশন',
    notifyPopupTitle: 'দাতাদের জানানো হয়েছে',
    notifyPopupDesc: 'বর্তমান অনুরোধের জন্য শীর্ষ মিল পাওয়া দাতাদের জানানো হয়েছে।'
  },
  mr: {
    pageTitle: 'BloodNet - स्मार्ट रक्तदाता नेटवर्क',
    brandTag: 'स्मार्ट रक्तदाता नेटवर्क',
    langLabel: 'भाषा',
    headerExplore: 'भूमिका पाहा',
    headerRequest: 'विनंती पाठवा',
    heroPill: 'AI-चालित · त्वरित',
    heroTitle: 'प्रत्येक सेकंद महत्त्वाचा. प्रत्येक रक्तदाता महत्त्वाचा.',
    heroDesc: 'दाते, रुग्णालये, आणि रक्तपेढ्या जोडणारे AI नेटवर्क; योग्य दाता काही सेकंदांत शोधते.',
    ctaPrimary: 'रक्तदाता बना',
    ctaSecondary: 'हे कसे काम करते',
    statDonors: 'सक्रिय रक्तदाता',
    statHospitals: 'भागीदार रुग्णालये',
    statLives: 'प्रभावित जीव',
    statResponse: 'सरासरी प्रतिसाद',
    criticalTag: 'तातडीची विनंती · 2 मिनिटांपूर्वी',
    liveTag: 'थेट',
    liveTitle: 'सेंट मार्था हॉस्पिटल · O+ रक्त',
    liveDesc: '2 युनिट · 3.2 किमी दूर',
    notifyTop: 'शीर्ष दात्यांना कळवा',
    featuresEyebrow: 'जीवन-मरणाच्या क्षणांसाठी बनवलेले',
    featuresTitle: 'हातची धावपळ समन्वित प्रतिसादात बदलणाऱ्या क्षमता.',
    feature1Title: 'आपत्कालीन अलर्ट',
    feature1Desc: 'विनंती येताच टॉप दात्यांना सूचना जाते.',
    feature2Title: 'उपलब्धता अंदाज',
    feature2Desc: 'आत्ता कोण प्रतिसाद देऊ शकेल हे अंदाज लावण्यास मदत करते.',
    feature3Title: 'प्राधान्य क्रमवारी',
    feature3Desc: 'अंतर, अलीकडीलता, प्रतिसाद इतिहास, आणि AI सिग्नलवर आधारित.',
    feature4Title: 'इतिहास आणि बॅज',
    feature4Desc: 'दान मैलाचे दगड, प्रमाणपत्रे, आणि नियमित दात्यांची ओळख.',
    feature5Title: 'नकाशा शोध',
    feature5Desc: 'योग्य दाते परिसरात शोधून संबंधितांना वरती दाखवतो.',
    feature6Title: 'प्रशासनिक विश्लेषण',
    feature6Desc: 'मागणी, पूर्तता वेग, आणि दाता टिकवून ठेवणे एकाच डॅशबोर्डवर.',
    rolesEyebrow: 'एक प्लॅटफॉर्म · चार भूमिका',
    rolesTitle: 'प्रत्येक वापरकर्त्याला त्यांच्या भूमिकेनुसार केंद्रित अनुभव मिळतो.',
    role1Mark: 'दाता',
    role1Title: 'अलर्ट मिळवा आणि प्रभाव पहा',
    role1Desc: 'जुळलेल्या विनंत्या पहा, पटकन प्रतिसाद द्या, आणि दान इतिहास जतन करा.',
    role2Mark: 'रुग्णालय',
    role2Title: 'ताबडतोब आपत्कालीन विनंत्या पाठवा',
    role2Desc: 'विनंती तयार करून जुळणाऱ्या दात्यांना त्वरित कळवा आणि प्रतिसाद पहा.',
    role3Mark: 'रक्तपेढी',
    role3Title: 'थेट साठा व्यवस्थापित करा',
    role3Desc: 'रक्त युनिट्स, पुरवठा ताण, आणि रुग्णालयांतील समन्वय पाहा.',
    role4Mark: 'प्रशासक',
    role4Title: 'संपूर्ण नेटवर्क पहा',
    role4Desc: 'थेट मेट्रिक्स, टिकाव, आणि प्रादेशिक हालचालींनी प्रणाली सक्रिय ठेवा.',
    impactEyebrow: 'हे का काम करते',
    impactTitle: 'प्रत्येक टप्प्यावर विलंब कमी करण्यासाठी डिझाइन केले.',
    impactDesc: 'BloodNet सुसंगतता नियम, रँक शिफारसी, आणि स्पष्ट प्रतिसाद प्रवाह एकत्र करतो.',
    faqEyebrow: 'वारंवार विचारले जाणारे प्रश्न',
    faqTitle: 'हे काय आहे, का उपयुक्त आहे, आणि का वेगळे आहे.',
    faq1Question: 'हे काय आहे?',
    faq1Answer: 'BloodNet हे रुग्णालये, दाते, आणि रक्तपेढ्यांना एका जागी जोडणारे नेटवर्क आहे.',
    faq2Question: 'हे उपयुक्त का आहे?',
    faq2Answer: 'हे वेळ वाचवते, योग्य दाता लवकर शोधते, आणि आपत्कालात प्रतिसाद वेगवान करते.',
    faq3Question: 'इतरांपेक्षा चांगले का?',
    faq3Answer: 'प्राधान्य, अंतर, आणि उपलब्धतेवर आधारित जुळणी; शोध यादृच्छिक नाही.',
    faq4Question: 'रुग्णालयांसाठी सोपे आहे का?',
    faq4Answer: 'हो, काही क्लिकमध्ये विनंती करून जुळलेल्या दात्यांना लगेच कळवता येते.',
    faq5Question: 'खरंच मदत होते का?',
    faq5Answer: 'हो, जलद जुळणी, स्पष्ट प्रक्रिया, आणि थेट सूचना मदत वेळेत पोहोचण्याची शक्यता वाढवतात.',
    footerBrandDesc: 'स्मार्ट रक्तदाता नेटवर्क',
    footerTeam: 'प्रकल्प संघ',
    team1: 'Angel Blessy (2547213)',
    team2: 'Enrita Fernandes (2547223)',
    footerLinks: 'द्रुत दुवे',
    footerLink1: 'वैशिष्ट्ये',
    footerLink2: 'भूमिका',
    footerLink3: 'परिणाम',
    legal1: 'MCA 2025–27 · CHRIST (Deemed to be University), Bangalore Central Campus',
    legal2: '© 2026 BloodNet',
    modalTitle: 'तातडीची विनंती पाठवा',
    modalDesc: 'ही डेमो रुग्णालय-ते-दाता कार्यप्रवाह दाखवते.',
    fieldTitle: 'रुग्ण / विनंती शीर्षक',
    fieldTitlePlaceholder: 'उदा. अपघात रुग्ण',
    fieldBloodGroup: 'रक्त गट',
    fieldUnits: 'आवश्यक युनिट्स',
    modalSubmit: 'जुळलेल्या दात्यांना कळवा',
    toastLanguage: 'भाषा मराठीत बदलली आहे.',
    toastNotify: 'शीर्ष 3 जुळलेल्या दात्यांना यशस्वीपणे कळवले.',
    toastRequest: 'तातडीची विनंती तयार केली. जुळलेल्या दात्यांना कळवले जात आहे.',
    ariaClose: 'विनंती फॉर्म बंद करा',
    notifyPopupKicker: 'सूचना',
    notifyPopupTitle: 'दात्यांना कळवले',
    notifyPopupDesc: 'सध्याच्या विनंतीसाठी शीर्ष जुळलेल्या दात्यांना कळवले आहे.'
  },
  gu: {
    pageTitle: 'BloodNet - સ્માર્ટ રક્તદાતા નેટવર્ક',
    brandTag: 'સ્માર્ટ રક્તદાતા નેટવર્ક',
    langLabel: 'ભાષા',
    headerExplore: 'ભૂમિકાઓ જુઓ',
    headerRequest: 'વિનંતી મોકલો',
    heroPill: 'AI-ચાલિત · તરત',
    heroTitle: 'દરેક સેકન્ડ મહત્વપૂર્ણ. દરેક દાતા મહત્વપૂર્ણ.',
    heroDesc: 'દાતાઓ, હોસ્પિટલો અને બ્લડ બેન્કને જોડતું AI નેટવર્ક; યોગ્ય દાતાને થોડા સેકન્ડમાં શોધે છે.',
    ctaPrimary: 'દાતા બનો',
    ctaSecondary: 'આ કેવી રીતે કામ કરે છે',
    statDonors: 'સક્રિય દાતા',
    statHospitals: 'ભાગીદાર હોસ્પિટલો',
    statLives: 'પ્રભાવિત જીવન',
    statResponse: 'સરેરાશ પ્રતિભાવ',
    criticalTag: 'તાત્કાલિક વિનંતી · 2 મિનિટ પહેલાં',
    liveTag: 'લાઇવ',
    liveTitle: 'સેન્ટ માર્થા હોસ્પિટલ · O+ રક્ત',
    liveDesc: '2 યુનિટ · 3.2 કિમી દૂર',
    notifyTop: 'ટોચના દાતાઓને જાણ કરો',
    featuresEyebrow: 'જીવન-મરણ ક્ષણો માટે બનાવેલું',
    featuresTitle: 'હાથની દોડધામને સમન્વિત પ્રતિભાવમાં ફેરવતી ક્ષમતાઓ.',
    feature1Title: 'તાત્કાલિક એલર્ટ્સ',
    feature1Desc: 'વિનંતી આવતા જ ટોચના દાતાઓને સૂચના જાય છે.',
    feature2Title: 'ઉપલબ્ધતા અનુમાન',
    feature2Desc: 'હમણાં કોણ જવાબ આપી શકે તે અંદાજવામાં મદદ કરે છે.',
    feature3Title: 'પ્રાથમિકતા ક્રમાંકન',
    feature3Desc: 'અંતર, તાજગી, પ્રતિભાવ ઇતિહાસ, અને AI સિગ્નલ આધારે.',
    feature4Title: 'ઇતિહાસ અને બેજ',
    feature4Desc: 'દાન માઇલસ્ટોન, પ્રમાણપત્રો, અને નિયમિત દાતાઓની ઓળખ.',
    feature5Title: 'નકશો શોધ',
    feature5Desc: 'યોગ્ય દાતાઓને આસપાસ શોધી સંબંધિતને ઉપર બતાવે છે.',
    feature6Title: 'પ્રશાસન વિશ્લેષણ',
    feature6Desc: 'માગ, પૂર્ણતા ગતિ, અને દાતા જાળવણી એક જ ડેશબોર્ડમાં જુઓ.',
    rolesEyebrow: 'એક પ્લેટફોર્મ · ચાર ભૂમિકાઓ',
    rolesTitle: 'દરેક વપરાશકર્તાને તેમની ભૂમિકા મુજબ કેન્દ્રિત અનુભવ મળે છે.',
    role1Mark: 'દાતા',
    role1Title: 'એલર્ટ મેળવો અને અસર જુઓ',
    role1Desc: 'મિલેલી વિનંતીઓ જુઓ, ઝડપથી પ્રતિભાવ આપો, અને દાન ઇતિહાસ જાળવો.',
    role2Mark: 'હોસ્પિટલ',
    role2Title: 'તાત્કાલિક તાકીદની વિનંતીઓ મોકલો',
    role2Desc: 'વિનંતી બનાવો, યોગ્ય દાતાઓને મેળવો, અને પ્રતિભાવ રિયલ ટાઇમમાં જુઓ.',
    role3Mark: 'બ્લડ બેન્ક',
    role3Title: 'લાઇવ ઇન્વેન્ટરી સંભાળો',
    role3Desc: 'રક્ત યુનિટ્સ ટ્રેક કરો, સપ્લાય દબાણ જુઓ, અને હોસ્પિટલ સાથે સમન્વય કરો.',
    role4Mark: 'એડમિન',
    role4Title: 'સમગ્ર નેટવર્ક જુઓ',
    role4Desc: 'લાઇવ મેટ્રિક્સ, જાળવણી, અને પ્રાદેશિક પ્રવૃત્તિથી સિસ્ટમને સક્રિય રાખો.',
    impactEyebrow: 'આ કેમ કામ કરે છે',
    impactTitle: 'દરેક તબક્કે વિલંબ ઘટાડવા માટે ડિઝાઇન કર્યું છે.',
    impactDesc: 'BloodNet સુસંગતતા નિયમો, ક્રમબદ્ધ ભલામણો, અને સ્પષ્ટ પ્રતિભાવ પ્રવાહ જોડે છે.',
    faqEyebrow: 'વારંવાર પૂછાતા પ્રશ્નો',
    faqTitle: 'આ શું છે, કેમ ઉપયોગી છે, અને કેમ અલગ છે.',
    faq1Question: 'આ શું છે?',
    faq1Answer: 'BloodNet એ નેટવર્ક છે જે હોસ્પિટલો, દાતાઓ, અને બ્લડ બેન્કને એક જગ્યાએ જોડે છે.',
    faq2Question: 'આ કેમ ઉપયોગી છે?',
    faq2Answer: 'આ સમય બચાવે છે, યોગ્ય દાતાને ઝડપી શોધે છે, અને તાત્કાલિક સ્થિતિમાં પ્રતિભાવ ઝડપી કરે છે.',
    faq3Question: 'બીજાઓ કરતા કેમ સારું?',
    faq3Answer: 'પ્રાથમિકતા, અંતર, અને ઉપલબ્ધતા આધારે મેળવે છે; શોધ રૅન્ડમ નથી.',
    faq4Question: 'હોસ્પિટલ માટે સરળ છે?',
    faq4Answer: 'હા, થોડા ક્લિકમાં વિનંતી કરીને મેળ થયેલા દાતાઓને તરત જાણ કરી શકાય છે.',
    faq5Question: 'ખરેખર મદદ કરે છે?',
    faq5Answer: 'હા, ઝડપી મેળ, સ્પષ્ટ પ્રક્રિયા, અને લાઇવ નોટિફિકેશન્સ મદદ સમયસર પહોંચવાની શક્યતા વધારે છે.',
    footerBrandDesc: 'સ્માર્ટ રક્તદાતા નેટવર્ક',
    footerTeam: 'પ્રોજેક્ટ ટીમ',
    team1: 'Angel Blessy (2547213)',
    team2: 'Enrita Fernandes (2547223)',
    footerLinks: 'ઝડપી લિંક્સ',
    footerLink1: 'વિશેષતાઓ',
    footerLink2: 'ભૂમિકાઓ',
    footerLink3: 'અસર',
    legal1: 'MCA 2025–27 · CHRIST (Deemed to be University), Bangalore Central Campus',
    legal2: '© 2026 BloodNet',
    modalTitle: 'તાત્કાલિક વિનંતી મોકલો',
    modalDesc: 'આ ડેમો હોસ્પિટલ-થી-દાતા વર્કફ્લો બતાવે છે.',
    fieldTitle: 'દર્દી / વિનંતી શીર્ષક',
    fieldTitlePlaceholder: 'ઉદા. અકસ્માત દર્દી',
    fieldBloodGroup: 'રક્ત જૂથ',
    fieldUnits: 'જરૂરી યુનિટ્સ',
    modalSubmit: 'મેળ થયેલા દાતાઓને જાણ કરો',
    toastLanguage: 'ભાષા ગુજરાતીમાં બદલાઈ છે.',
    toastNotify: 'ટોચના 3 મેળ થયેલા દાતાઓને સફળતાપૂર્વક જાણ કરી.',
    toastRequest: 'તાત્કાલિક વિનંતી બનાવાઈ. મેળ થયેલા દાતાઓને જાણ કરવામાં આવી રહી છે.',
    ariaClose: 'વિનંતી ફોર્મ બંધ કરો',
    notifyPopupKicker: 'સૂચના',
    notifyPopupTitle: 'દાતાઓને જાણ કરી',
    notifyPopupDesc: 'વર્તમાન વિનંતી માટે ટોચના મેળ થયેલા દાતાઓને જાણ કરવામાં આવી છે.'
  },
  pa: {
    pageTitle: 'BloodNet - ਸਮਾਰਟ ਰਕਤਦਾਤਾ ਨੈੱਟਵਰਕ',
    brandTag: 'ਸਮਾਰਟ ਰਕਤਦਾਤਾ ਨੈੱਟਵਰਕ',
    langLabel: 'ਭਾਸ਼ਾ',
    headerExplore: 'ਭੂਮਿਕਾਵਾਂ ਵੇਖੋ',
    headerRequest: 'ਬੇਨਤੀ ਭੇਜੋ',
    heroPill: 'AI-ਚਾਲਿਤ · ਤੁਰੰਤ',
    heroTitle: 'ਹਰ ਸੈਕਿੰਡ ਮਹੱਤਵਪੂਰਣ ਹੈ। ਹਰ ਦਾਤਾ ਮਹੱਤਵਪੂਰਣ ਹੈ।',
    heroDesc: 'ਦਾਤਿਆਂ, ਹਸਪਤਾਲਾਂ, ਅਤੇ ਬਲੱਡ ਬੈਂਕਾਂ ਨੂੰ ਜੋੜਣ ਵਾਲਾ AI ਨੈੱਟਵਰਕ; ਸਹੀ ਦਾਤਾ ਕੁਝ ਸੈਕਿੰਡਾਂ ਵਿੱਚ ਲੱਭਦਾ ਹੈ।',
    ctaPrimary: 'ਦਾਤਾ ਬਣੋ',
    ctaSecondary: 'ਇਹ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ',
    statDonors: 'ਸਕ੍ਰਿਯ ਦਾਤਾ',
    statHospitals: 'ਭਾਗੀਦਾਰ ਹਸਪਤਾਲ',
    statLives: 'ਪ੍ਰਭਾਵਿਤ ਜ਼ਿੰਦਗੀਆਂ',
    statResponse: 'ਔਸਤ ਜਵਾਬ',
    criticalTag: 'ਤੁਰੰਤ ਬੇਨਤੀ · 2 ਮਿੰਟ ਪਹਿਲਾਂ',
    liveTag: 'ਲਾਈਵ',
    liveTitle: 'ਸੇਂਟ ਮਾਰਥਾ ਹਸਪਤਾਲ · O+ ਖੂਨ',
    liveDesc: '2 ਯੂਨਿਟ · 3.2 ਕਿਮੀ ਦੂਰ',
    notifyTop: 'ਸਿਖਰਲੇ ਦਾਤਿਆਂ ਨੂੰ ਸੁਚਿਤ ਕਰੋ',
    featuresEyebrow: 'ਜੀਵਨ-ਮੌਤ ਦੇ ਪਲਾਂ ਲਈ ਬਣਾਇਆ ਗਿਆ',
    featuresTitle: 'ਹੱਥੀ ਦੌੜਧੂਪ ਨੂੰ ਸਮਨਵਿਤ ਜਵਾਬ ਵਿੱਚ ਬਦਲਣ ਵਾਲੀਆਂ ਸਮਰੱਥਾਵਾਂ।',
    feature1Title: 'ਤੁਰੰਤ ਚੇਤਾਵਨੀਆਂ',
    feature1Desc: 'ਬੇਨਤੀ ਆਉਂਦੇ ਹੀ ਟਾਪ ਦਾਤਿਆਂ ਤੱਕ ਨੋਟੀਫਿਕੇਸ਼ਨ ਪਹੁੰਚਦਾ ਹੈ।',
    feature2Title: 'ਉਪਲਬਧਤਾ ਅਨੁਮਾਨ',
    feature2Desc: 'ਹੁਣ ਕੌਣ ਜਵਾਬ ਦੇ ਸਕਦਾ ਹੈ, ਇਹ ਅੰਦਾਜ਼ਾ ਲਗਾਉਣ ਵਿੱਚ ਮਦਦ ਕਰਦਾ ਹੈ।',
    feature3Title: 'ਪ੍ਰਾਥਮਿਕਤਾ ਰੈਂਕਿੰਗ',
    feature3Desc: 'ਦੂਰੀ, ਤਾਜ਼ਗੀ, ਜਵਾਬ ਇਤਿਹਾਸ, ਅਤੇ AI ਸਿਗਨਲ ਦੇ ਆਧਾਰ ' + 'ਤੇ.',
    feature4Title: 'ਇਤਿਹਾਸ ਅਤੇ ਬੈਜ',
    feature4Desc: 'ਦਾਨ ਮੀਲਸਟੋਨ, ਸਰਟੀਫਿਕੇਟ, ਅਤੇ ਨਿਯਮਤ ਦਾਤਿਆਂ ਦੀ ਪਛਾਣ।',
    feature5Title: 'ਮੈਪ ਖੋਜ',
    feature5Desc: 'ਉਪਯੁਕਤ ਦਾਤਿਆਂ ਨੂੰ ਨੇੜੇ ਲੱਭ ਕੇ ਸੰਬੰਧਤਾਂ ਨੂੰ ਉੱਪਰ ਦਿਖਾਉਂਦਾ ਹੈ।',
    feature6Title: 'ਐਡਮਿਨ ਵਿਸ਼ਲੇਸ਼ਣ',
    feature6Desc: 'ਮੰਗ, ਪੂਰਾ ਕਰਨ ਦੀ ਗਤੀ, ਅਤੇ ਦਾਤਾ ਬਣੇ ਰਹਿਣ ਨੂੰ ਇੱਕ ਡੈਸ਼ਬੋਰਡ ' + 'ਚ ਵੇਖੋ.',
    rolesEyebrow: 'ਇੱਕ ਪਲੇਟਫਾਰਮ · ਚਾਰ ਭੂਮਿਕਾਵਾਂ',
    rolesTitle: 'ਹਰ ਯੂਜ਼ਰ ਨੂੰ ਆਪਣੀ ਭੂਮਿਕਾ ਅਨੁਸਾਰ ਕੇਂਦ੍ਰਿਤ ਅਨੁਭਵ ਮਿਲਦਾ ਹੈ।',
    role1Mark: 'ਦਾਤਾ',
    role1Title: 'ਅਲਰਟ ਪ੍ਰਾਪਤ ਕਰੋ ਅਤੇ ਪ੍ਰਭਾਵ ਵੇਖੋ',
    role1Desc: 'ਮਿਲੀਆਂ ਬੇਨਤੀਆਂ ਵੇਖੋ, ਤੇਜ਼ ਜਵਾਬ ਦਿਓ, ਅਤੇ ਦਾਨ ਇਤਿਹਾਸ ਵੇਖੋ।',
    role2Mark: 'ਹਸਪਤਾਲ',
    role2Title: 'ਤੁਰੰਤ ਐਮਰਜੈਂਸੀ ਬੇਨਤੀ ਭੇਜੋ',
    role2Desc: 'ਬੇਨਤੀ ਬਣਾਓ, ਯੋਗ ਦਾਤਿਆਂ ਨੂੰ ਮਿਲਾਓ, ਅਤੇ ਜਵਾਬ ਨੂੰ ਰੀਅਲ ਟਾਈਮ ' + 'ਚ ਵੇਖੋ.',
    role3Mark: 'ਬਲੱਡ ਬੈਂਕ',
    role3Title: 'ਲਾਈਵ ਇਨਵੈਂਟਰੀ ਸੰਭਾਲੋ',
    role3Desc: 'ਖੂਨ ਯੂਨਿਟ ਟ੍ਰੈਕ ਕਰੋ, ਸਪਲਾਈ ਦਬਾਅ ਵੇਖੋ, ਅਤੇ ਹਸਪਤਾਲਾਂ ਨਾਲ ਸਮਨਵਯ ਕਰੋ।',
    role4Mark: 'ਐਡਮਿਨ',
    role4Title: 'ਪੂਰਾ ਨੈੱਟਵਰਕ ਵੇਖੋ',
    role4Desc: 'ਲਾਈਵ ਮੈਟਰਿਕਸ, ਰੀਟੇਨਸ਼ਨ ਇਨਸਾਈਟ, ਅਤੇ ਖੇਤਰੀ ਸਰਗਰਮੀ ਨਾਲ ਸਿਸਟਮ ਨੂੰ ਸਚਲ ਰੱਖੋ।',
    impactEyebrow: 'ਇਹ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ',
    impactTitle: 'ਹਰ ਕਦਮ ' + 'ਤੇ ਦੇਰੀ ਘਟਾਉਣ ਲਈ ਬਣਾਇਆ ਗਿਆ.',
    impactDesc: 'BloodNet ਮਿਲਾਨ ਨਿਯਮ, ਰੈਂਕ ਕੀਤੀਆਂ ਸਿਫ਼ਾਰਸ਼ਾਂ, ਅਤੇ ਸਪਸ਼ਟ ਜਵਾਬ ਵਰਕਫਲੋ ਨੂੰ ਜੋੜਦਾ ਹੈ।',
    faqEyebrow: 'ਅਕਸਰ ਪੁੱਛੇ ਜਾਂਦੇ ਪ੍ਰਸ਼ਨ',
    faqTitle: 'ਇਹ ਕੀ ਹੈ, ਕਿਉਂ ਫਾਇਦੇਮੰਦ ਹੈ, ਅਤੇ ਕਿਉਂ ਵੱਖਰਾ ਹੈ.',
    faq1Question: 'ਇਹ ਕੀ ਹੈ?',
    faq1Answer: 'BloodNet ਇੱਕ ਨੈੱਟਵਰਕ ਹੈ ਜੋ ਹਸਪਤਾਲਾਂ, ਦਾਤਿਆਂ, ਅਤੇ ਬਲੱਡ ਬੈਂਕਾਂ ਨੂੰ ਇੱਕ ਥਾਂ ਜੋੜਦਾ ਹੈ।',
    faq2Question: 'ਇਹ ਕਿਉਂ ਫਾਇਦੇਮੰਦ ਹੈ?',
    faq2Answer: 'ਇਹ ਸਮਾਂ ਬਚਾਉਂਦਾ ਹੈ, ਸਹੀ ਦਾਤਾ ਜਲਦੀ ਲੱਭਦਾ ਹੈ, ਅਤੇ ਐਮਰਜੈਂਸੀ ਵਿੱਚ ਜਵਾਬ ਤੇਜ਼ ਕਰਦਾ ਹੈ।',
    faq3Question: 'ਹੋਰਾਂ ਨਾਲੋਂ ਕਿਉਂ ਵਧੀਆ?',
    faq3Answer: 'ਪ੍ਰਾਥਮਿਕਤਾ, ਦੂਰੀ, ਅਤੇ ਉਪਲਬਧਤਾ ਦੇ ਆਧਾਰ ' + 'ਤੇ ਮਿਲਾਉਂਦਾ ਹੈ; ਖੋਜ ਯਾਦਰੱਚਿਕ ਨਹੀਂ.',
    faq4Question: 'ਕੀ ਹਸਪਤਾਲਾਂ ਲਈ ਸੌਖਾ ਹੈ?',
    faq4Answer: 'ਹਾਂ, ਕੁਝ ਕਲਿੱਕਾਂ ਵਿੱਚ ਬੇਨਤੀ ਕਰ ਕੇ ਮਿਲੇ ਦਾਤਿਆਂ ਨੂੰ ਤੁਰੰਤ ਸੂਚਿਤ ਕਰ ਸਕਦੇ ਹਨ।',
    faq5Question: 'ਕੀ ਅਸਲ ਵਿੱਚ ਮਦਦ ਕਰਦਾ ਹੈ?',
    faq5Answer: 'ਹਾਂ, ਤੇਜ਼ ਮਿਲਾਨ, ਸਪਸ਼ਟ ਪ੍ਰਕਿਰਿਆ, ਅਤੇ ਲਾਈਵ ਨੋਟੀਫਿਕੇਸ਼ਨ ਸਮੇਂ ' + 'ਤੇ ਮਦਦ ਪਹੁੰਚਣ ਦੀ ਸੰਭਾਵਨਾ ਵਧਾਉਂਦੇ ਹਨ.',
    footerBrandDesc: 'ਸਮਾਰਟ ਰਕਤਦਾਤਾ ਨੈੱਟਵਰਕ',
    footerTeam: 'ਪ੍ਰੋਜੈਕਟ ਟੀਮ',
    team1: 'Angel Blessy (2547213)',
    team2: 'Enrita Fernandes (2547223)',
    footerLinks: 'ਤੁਰੰਤ ਲਿੰਕ',
    footerLink1: 'ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ',
    footerLink2: 'ਭੂਮਿਕਾਵਾਂ',
    footerLink3: 'ਪ੍ਰਭਾਵ',
    legal1: 'MCA 2025–27 · CHRIST (Deemed to be University), Bangalore Central Campus',
    legal2: '© 2026 BloodNet',
    modalTitle: 'ਤੁਰੰਤ ਬੇਨਤੀ ਭੇਜੋ',
    modalDesc: 'ਇਹ ਡੈਮੋ ਹਸਪਤਾਲ-ਤੋਂ-ਦਾਤਾ ਵਰਕਫਲੋ ਦਿਖਾਉਂਦਾ ਹੈ।',
    fieldTitle: 'ਮਰੀਜ਼ / ਬੇਨਤੀ ਸਿਰਲੇਖ',
    fieldTitlePlaceholder: 'ਜਿਵੇਂ: ਹਾਦਸਾ ਮਰੀਜ਼',
    fieldBloodGroup: 'ਖੂਨ ਸਮੂਹ',
    fieldUnits: 'ਲੋੜੀਂਦੇ ਯੂਨਿਟ',
    modalSubmit: 'ਮਿਲੇ ਦਾਤਿਆਂ ਨੂੰ ਸੂਚਿਤ ਕਰੋ',
    toastLanguage: 'ਭਾਸ਼ਾ ਪੰਜਾਬੀ ਵਿੱਚ ਬਦਲ ਗਈ ਹੈ।',
    toastNotify: 'ਸਿਖਰਲੇ 3 ਮਿਲੇ ਦਾਤਿਆਂ ਨੂੰ ਸਫਲਤਾਪੂਰਵਕ ਸੂਚਿਤ ਕੀਤਾ ਗਿਆ।',
    toastRequest: 'ਤੁਰੰਤ ਬੇਨਤੀ ਬਣਾਈ ਗਈ। ਮਿਲੇ ਦਾਤਿਆਂ ਨੂੰ ਸੂਚਿਤ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ।',
    ariaClose: 'ਬੇਨਤੀ ਫਾਰਮ ਬੰਦ ਕਰੋ',
    notifyPopupKicker: 'ਸੂਚਨਾ',
    notifyPopupTitle: 'ਦਾਤਿਆਂ ਨੂੰ ਸੂਚਿਤ ਕੀਤਾ ਗਿਆ',
    notifyPopupDesc: 'ਮੌਜੂਦਾ ਬੇਨਤੀ ਲਈ ਸਿਖਰਲੇ ਮਿਲੇ ਦਾਤਿਆਂ ਨੂੰ ਸੂਚਿਤ ਕਰ ਦਿੱਤਾ ਗਿਆ ਹੈ।'
  },
  ur: {
    pageTitle: 'BloodNet - اسمارٹ خون عطیہ دہندہ نیٹ ورک',
    brandTag: 'اسمارٹ خون عطیہ دہندہ نیٹ ورک',
    langLabel: 'زبان',
    headerExplore: 'کردار دیکھیں',
    headerRequest: 'درخواست بھیجیں',
    heroPill: 'AI سے چلنے والا · فوری',
    heroTitle: 'ہر سیکنڈ اہم ہے۔ ہر عطیہ دہندہ اہم ہے۔',
    heroDesc: 'ایک AI نیٹ ورک جو عطیہ دہندگان، اسپتالوں، اور بلڈ بینکوں کو جوڑتا ہے؛ صحیح عطیہ دہندہ چند سیکنڈ میں مل جاتا ہے۔',
    ctaPrimary: 'عطیہ دہندہ بنیں',
    ctaSecondary: 'یہ کیسے کام کرتا ہے',
    statDonors: 'فعال عطیہ دہندگان',
    statHospitals: 'شراکت دار اسپتال',
    statLives: 'متاثرہ زندگیاں',
    statResponse: 'اوسط ردِعمل',
    criticalTag: 'ہنگامی درخواست · 2 منٹ پہلے',
    liveTag: 'لائیو',
    liveTitle: 'سینٹ مارٹھا اسپتال · O+ خون',
    liveDesc: '2 یونٹ · 3.2 کلومیٹر دور',
    notifyTop: 'اوپر والے عطیہ دہندگان کو اطلاع دیں',
    featuresEyebrow: 'زندگی اور موت کے لمحوں کے لیے بنایا گیا',
    featuresTitle: 'ایسی صلاحیتیں جو ہاتھ کی دوڑ کو منظم ردعمل میں بدل دیتی ہیں۔',
    feature1Title: 'ہنگامی الرٹس',
    feature1Desc: 'درخواست آتے ہی اوپر درج عطیہ دہندگان تک اطلاع پہنچتی ہے۔',
    feature2Title: 'دستیابی کی پیش گوئی',
    feature2Desc: 'اب کون جواب دے سکتا ہے یہ اندازہ لگانے میں مدد کرتا ہے۔',
    feature3Title: 'ترجیحی درجہ بندی',
    feature3Desc: 'فاصلہ، تازگی، ردعمل کی تاریخ، اور AI سگنل کی بنیاد پر۔',
    feature4Title: 'تاریخ اور بیجز',
    feature4Desc: 'عطیہ کے سنگِ میل، سرٹیفکیٹس، اور مستقل عطیہ دہندگان کی شناخت۔',
    feature5Title: 'نقشہ تلاش',
    feature5Desc: 'موزوں عطیہ دہندگان کو قریب میں تلاش کر کے متعلقہ افراد کو اوپر لاتا ہے۔',
    feature6Title: 'ایڈمن اینالیٹکس',
    feature6Desc: 'طلب، تکمیل کی رفتار، اور عطیہ دہندگان کی برقراری ایک ڈیش بورڈ میں دیکھیں۔',
    rolesEyebrow: 'ایک پلیٹ فارم · چار کردار',
    rolesTitle: 'ہر صارف کو اپنے کردار کے مطابق مرکوز تجربہ ملتا ہے۔',
    role1Mark: 'عطیہ دہندہ',
    role1Title: 'الرٹس حاصل کریں اور اثر دیکھیں',
    role1Desc: 'ملی ہوئی درخواستیں دیکھیں، جلد جواب دیں، اور عطیہ کی تاریخ محفوظ رکھیں۔',
    role2Mark: 'اسپتال',
    role2Title: 'فوراً ہنگامی درخواستیں بھیجیں',
    role2Desc: 'درخواست بنائیں، اہل عطیہ دہندگان کو میچ کریں، اور ردعمل لائیو دیکھیں۔',
    role3Mark: 'بلڈ بینک',
    role3Title: 'لائیو انوینٹری سنبھالیں',
    role3Desc: 'خون کی یونٹس ٹریک کریں، سپلائی دباؤ دیکھیں، اور اسپتالوں کے ساتھ رابطہ رکھیں۔',
    role4Mark: 'ایڈمن',
    role4Title: 'پورا نیٹ ورک دیکھیں',
    role4Desc: 'لائیو میٹرکس، برقرار رکھنے کے اشارے، اور علاقائی سرگرمی سے نظام کو متحرک رکھیں۔',
    impactEyebrow: 'یہ کیوں کام کرتا ہے',
    impactTitle: 'ہر مرحلے میں تاخیر کم کرنے کے لیے ڈیزائن کیا گیا۔',
    impactDesc: 'BloodNet مطابقت کے اصول، رینک شدہ تجاویز، اور واضح ردعمل کے بہاؤ کو جوڑتا ہے۔',
    faqEyebrow: 'اکثر پوچھے گئے سوالات',
    faqTitle: 'یہ کیا ہے، کیوں مفید ہے، اور کیوں منفرد ہے۔',
    faq1Question: 'یہ کیا ہے؟',
    faq1Answer: 'BloodNet ایک نیٹ ورک ہے جو اسپتالوں، عطیہ دہندگان، اور بلڈ بینکوں کو ایک جگہ جوڑتا ہے۔',
    faq2Question: 'یہ کیوں مفید ہے؟',
    faq2Answer: 'یہ وقت بچاتا ہے، صحیح عطیہ دہندہ جلد ڈھونڈتا ہے، اور ایمرجنسی میں ردعمل تیز کرتا ہے۔',
    faq3Question: 'دوسروں سے بہتر کیوں؟',
    faq3Answer: 'ترجیح، فاصلے، اور دستیابی کی بنیاد پر میچ کرتا ہے؛ تلاش بےترتیب نہیں۔',
    faq4Question: 'کیا یہ اسپتالوں کے لیے آسان ہے؟',
    faq4Answer: 'جی ہاں، چند کلکس میں درخواست دے کر میچ شدہ عطیہ دہندگان کو فوراً اطلاع دی جا سکتی ہے۔',
    faq5Question: 'کیا واقعی مدد کرتا ہے؟',
    faq5Answer: 'جی ہاں، تیز میچنگ، واضح عمل، اور لائیو نوٹیفکیشن مدد وقت پر پہنچنے کے امکانات بڑھاتے ہیں۔',
    footerBrandDesc: 'اسمارٹ خون عطیہ دہندہ نیٹ ورک',
    footerTeam: 'پروجیکٹ ٹیم',
    team1: 'Angel Blessy (2547213)',
    team2: 'Enrita Fernandes (2547223)',
    footerLinks: 'فوری لنکس',
    footerLink1: 'خصوصیات',
    footerLink2: 'کردار',
    footerLink3: 'اثر',
    legal1: 'MCA 2025–27 · CHRIST (Deemed to be University), Bangalore Central Campus',
    legal2: '© 2026 BloodNet',
    modalTitle: 'ہنگامی درخواست بھیجیں',
    modalDesc: 'یہ ڈیمو اسپتال سے عطیہ دہندہ ورک فلو دکھاتا ہے۔',
    fieldTitle: 'مریض / درخواست عنوان',
    fieldTitlePlaceholder: 'مثلاً: حادثہ مریض',
    fieldBloodGroup: 'خون کا گروپ',
    fieldUnits: 'ضروری یونٹس',
    modalSubmit: 'میچ شدہ عطیہ دہندگان کو اطلاع دیں',
    toastLanguage: 'زبان اردو میں بدل دی گئی ہے۔',
    toastNotify: 'اوپر والے 3 میچ شدہ عطیہ دہندگان کو کامیابی سے اطلاع دی گئی۔',
    toastRequest: 'ہنگامی درخواست بن گئی۔ میچ شدہ عطیہ دہندگان کو اطلاع دی جا رہی ہے۔',
    ariaClose: 'درخواست فارم بند کریں',
    notifyPopupKicker: 'اطلاع',
    notifyPopupTitle: 'عطیہ دہندگان کو اطلاع دی گئی',
    notifyPopupDesc: 'موجودہ درخواست کے لیے اوپر والے میچ شدہ عطیہ دہندگان کو اطلاع دے دی گئی ہے۔'
  }
};

function showToast(message) {
  if (!toastEl) {
    return;
  }
  toastEl.textContent = message;
  toastEl.classList.add('show');
  clearTimeout(toastTimer);
  toastTimer = setTimeout(() => toastEl.classList.remove('show'), 2400);
}

function applyLanguage(language) {
  const strings = translations[language] || translations.en;
  document.title = strings.pageTitle;
  document.documentElement.lang = language;

  document.querySelectorAll('[data-i18n]').forEach((node) => {
    const key = node.getAttribute('data-i18n');
    if (strings[key] !== undefined) {
      node.innerHTML = strings[key];
    }
  });

  document.querySelectorAll('[data-i18n-placeholder]').forEach((node) => {
    const key = node.getAttribute('data-i18n-placeholder');
    if (strings[key] !== undefined) {
      node.setAttribute('placeholder', strings[key]);
    }
  });

  const closeButton = document.querySelector('#closeModal');
  if (closeButton) {
    closeButton.setAttribute('aria-label', strings.ariaClose);
  }

  document.querySelectorAll('[data-i18n-popup]').forEach((node) => {
    const key = node.getAttribute('data-i18n-popup');
    if (strings[key] !== undefined) {
      node.textContent = strings[key];
    }
  });
}

languageSelect?.addEventListener('change', (event) => {
  const language = event.target.value;
  applyLanguage(language);
  showToast(translations[language]?.toastLanguage || translations.en.toastLanguage);
});

document.querySelector('#notifyTop')?.addEventListener('click', () => {
  const language = languageSelect?.value || 'en';
  showToast(translations[language]?.toastNotify || translations.en.toastNotify);
  openNotifyPopup(language);
});

document.querySelector('#becomeDonor')?.addEventListener('click', () => {
  modalEl?.classList.add('open');
  modalEl?.setAttribute('aria-hidden', 'false');
});

document.querySelector('#openRequest')?.addEventListener('click', () => {
  modalEl?.classList.add('open');
  modalEl?.setAttribute('aria-hidden', 'false');
});

document.querySelector('#closeModal')?.addEventListener('click', closeModal);

modalEl?.addEventListener('click', (event) => {
  if (event.target === modalEl) {
    closeModal();
  }
});

document.querySelector('#emergencyForm')?.addEventListener('submit', (event) => {
  event.preventDefault();
  closeModal();
  const language = languageSelect?.value || 'en';
  showToast(translations[language]?.toastRequest || translations.en.toastRequest);
});

document.querySelector('#mobile')?.addEventListener('click', () => {
  navLinks?.parentElement?.classList.toggle('open');
});

navLinks?.querySelectorAll('a').forEach((link) => {
  link.addEventListener('click', () => {
    navLinks.parentElement?.classList.remove('open');
  });
});

function closeModal() {
  modalEl?.classList.remove('open');
  modalEl?.setAttribute('aria-hidden', 'true');
}

function openNotifyPopup(language) {
  if (!notifyPopupEl) {
    return;
  }

  const strings = translations[language] || translations.en;
  const title = notifyPopupEl.querySelector('#notifyPopupTitle');
  const kicker = notifyPopupEl.querySelector('.notify-kicker');
  const description = notifyPopupEl.querySelector('[data-i18n="notifyPopupDesc"]');

  if (title) title.textContent = strings.notifyPopupTitle;
  if (kicker) kicker.textContent = strings.notifyPopupKicker;
  if (description) description.textContent = strings.notifyPopupDesc;

  notifyPopupEl.classList.add('open');
  notifyPopupEl.setAttribute('aria-hidden', 'false');
}

document.querySelector('#closeNotifyPopup')?.addEventListener('click', closeNotifyPopup);
notifyPopupEl?.addEventListener('click', (event) => {
  if (event.target === notifyPopupEl) {
    closeNotifyPopup();
  }
});

function closeNotifyPopup() {
  notifyPopupEl?.classList.remove('open');
  notifyPopupEl?.setAttribute('aria-hidden', 'true');
}

if (languageSelect) {
  languageSelect.value = 'en';
}

applyLanguage('en');
